<?php

namespace Database\Seeders;

use App\Models\ServiceItem;
use Illuminate\Database\Seeder;

class ServiceItemSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            [
                'title'       => ['en' => 'Brochure Websites', 'pl' => 'Strony wizytówkowe', 'pt' => 'Sites Institucionais'],
                'badge_text'  => ['en' => 'Most Popular', 'pl' => 'Najpopularniejsze', 'pt' => 'Mais Popular'],
                'description' => [
                    'en' => 'Professional, mobile-first websites that create the right first impression and generate enquiries.',
                    'pl' => 'Profesjonalne strony firmowe mobile-first, które budują zaufanie i generują zapytania.',
                    'pt' => 'Websites profissionais mobile-first que criam a primeira impressão certa e geram pedidos de contacto.',
                ],
                'body' => [
                    'en' => '<p>Your website is your most important marketing asset. We build clean, fast, mobile-first brochure sites that represent your brand professionally and turn visitors into enquiries.</p><p>Every project starts with a discovery session to understand your audience, goals, and competitors. We then design and develop a site that looks great on every device, loads in under 2 seconds, and is optimised for search engines from day one.</p><h2>Our Process</h2><ol><li>Discovery &amp; Strategy</li><li>Wireframes &amp; Design</li><li>Development &amp; CMS Setup</li><li>Testing &amp; Launch</li><li>Post-launch Support</li></ol>',
                    'pl' => '<p>Twoja strona internetowa to Twoje najważniejsze narzędzie marketingowe. Tworzymy szybkie, eleganckie strony firmowe mobile-first, które reprezentują Twoją markę i zamieniają odwiedzających w klientów.</p><p>Każdy projekt zaczyna się od sesji discovery — rozumiemy Twoje cele, grupę docelową i konkurencję. Następnie projektujemy i wdrażamy stronę, która świetnie wygląda na każdym urządzeniu, ładuje się poniżej 2 sekund i jest zoptymalizowana pod SEO od pierwszego dnia.</p><h2>Nasz proces</h2><ol><li>Discovery i strategia</li><li>Szkielety i projekt graficzny</li><li>Wdrożenie i konfiguracja CMS</li><li>Testy i launch</li><li>Wsparcie po uruchomieniu</li></ol>',
                    'pt' => '<p>O seu website é o seu ativo de marketing mais importante. Criamos sites institucionais rápidos, limpos e mobile-first que representam a sua marca profissionalmente e convertem visitantes em contactos.</p><p>Cada projeto começa com uma sessão de descoberta para entender o seu público, objetivos e concorrentes. Depois, desenhamos e desenvolvemos um site que fica ótimo em qualquer dispositivo, carrega em menos de 2 segundos e está otimizado para motores de busca desde o primeiro dia.</p><h2>O Nosso Processo</h2><ol><li>Descoberta e Estratégia</li><li>Wireframes e Design</li><li>Desenvolvimento e CMS</li><li>Testes e Lançamento</li><li>Suporte Pós-lançamento</li></ol>',
                ],
                'features' => [
                    ['text_en' => 'Mobile-first, fully responsive design',       'text_pl' => 'Projekt mobile-first, w pełni responsywny',       'text_pt' => 'Design mobile-first e totalmente responsivo'],
                    ['text_en' => 'Core Web Vitals optimised (LCP < 2s)',         'text_pl' => 'Zoptymalizowane Core Web Vitals (LCP < 2s)',         'text_pt' => 'Core Web Vitals otimizados (LCP < 2s)'],
                    ['text_en' => 'SEO-ready structure & meta tags',              'text_pl' => 'Struktura i metatagi zoptymalizowane pod SEO',       'text_pt' => 'Estrutura e metatags prontas para SEO'],
                    ['text_en' => 'Content management system (CMS) included',    'text_pl' => 'System zarządzania treścią (CMS) w cenie',           'text_pt' => 'Sistema de gestão de conteúdo (CMS) incluído'],
                    ['text_en' => 'Contact forms with spam protection',           'text_pl' => 'Formularze kontaktowe z ochroną antyspamową',        'text_pt' => 'Formulários de contacto com proteção anti-spam'],
                    ['text_en' => 'SSL certificate & secure hosting setup',       'text_pl' => 'Certyfikat SSL i bezpieczny hosting w konfiguracji', 'text_pt' => 'Certificado SSL e configuração de alojamento seguro'],
                ],
                'faq' => [
                    [
                        'q_en' => 'How long does it take to build a brochure website?',
                        'q_pl' => 'Jak długo trwa budowa strony wizytówkowej?',
                        'q_pt' => 'Quanto tempo demora a construir um site institucional?',
                        'a_en' => 'Typically 3–5 weeks depending on the number of pages and how quickly content and feedback are provided.',
                        'a_pl' => 'Zazwyczaj 3–5 tygodni, w zależności od liczby podstron i tempa dostarczania treści oraz feedbacku.',
                        'a_pt' => 'Normalmente 3 a 5 semanas, dependendo do número de páginas e da rapidez com que o conteúdo e o feedback são fornecidos.',
                    ],
                    [
                        'q_en' => 'Will I be able to update the website myself?',
                        'q_pl' => 'Czy będę mógł samodzielnie aktualizować stronę?',
                        'q_pt' => 'Poderei atualizar o website eu mesmo?',
                        'a_en' => 'Yes. We set up a user-friendly CMS so you can edit text, images, and pages without any technical knowledge.',
                        'a_pl' => 'Tak. Konfigurujemy przyjazny CMS, dzięki któremu możesz edytować treści, zdjęcia i podstrony bez wiedzy technicznej.',
                        'a_pt' => 'Sim. Configuramos um CMS fácil de usar para que possa editar textos, imagens e páginas sem qualquer conhecimento técnico.',
                    ],
                    [
                        'q_en' => 'What is included in the £799 price?',
                        'q_pl' => 'Co zawiera cena £799?',
                        'q_pt' => 'O que está incluído no preço de £799?',
                        'a_en' => 'Up to 5 pages, custom design, CMS, contact form, basic SEO setup, and 30 days of post-launch support.',
                        'a_pl' => 'Do 5 podstron, unikalny projekt graficzny, CMS, formularz kontaktowy, podstawowe SEO i 30 dni wsparcia po uruchomieniu.',
                        'a_pt' => 'Até 5 páginas, design personalizado, CMS, formulário de contacto, configuração básica de SEO e 30 dias de suporte pós-lançamento.',
                    ],
                ],
                'cta_label' => ['en' => 'Get a Free Quote', 'pl' => 'Zapytaj o wycenę', 'pt' => 'Pedir Orçamento'],
                'cta_url'   => '/contact',
                'meta_title' => [
                    'en' => 'Brochure Websites from £799 | Website Expert',
                    'pl' => 'Strony wizytówkowe od £799 | Website Expert',
                    'pt' => 'Sites Institucionais a partir de £799 | Website Expert',
                ],
                'meta_description' => [
                    'en' => 'Professional mobile-first brochure websites designed to generate enquiries. Fast, secure, SEO-ready. From £799.',
                    'pl' => 'Profesjonalne strony firmowe mobile-first generujące zapytania. Szybkie, bezpieczne, SEO-ready. Od £799.',
                    'pt' => 'Websites institucionais mobile-first profissionais para gerar contactos. Rápidos, seguros, prontos para SEO. A partir de £799.',
                ],
                'icon'        => 'monitor',
                'price_from'  => '£799',
                'link'        => '/services/brochure-websites',
                'slug'        => 'brochure-websites',
                'is_featured' => true,
                'is_active'   => true,
                'sort_order'  => 1,
            ],
            [
                'title'       => ['en' => 'E-Commerce Stores', 'pl' => 'Sklepy e-commerce', 'pt' => 'Lojas E-Commerce'],
                'badge_text'  => ['en' => 'High ROI', 'pl' => 'Wysoki ROI', 'pt' => 'Alto ROI'],
                'description' => [
                    'en' => 'Sell online with confidence. WooCommerce and headless solutions tailored to your products.',
                    'pl' => 'Szybkie, bezpieczne sklepy online z integracją płatności i systemu zamówień.',
                    'pt' => 'Venda online com confiança. Soluções WooCommerce e headless adaptadas aos seus produtos.',
                ],
                'body' => [
                    'en' => '<p>We build e-commerce stores that are designed to sell. From WooCommerce to fully headless React storefronts, we tailor every solution to your product catalogue, pricing model, and customer journey.</p><p>Our stores are fast, secure, and optimised for conversion — with streamlined checkouts, product filtering, and native integrations with Stripe, PayPal, and leading couriers.</p>',
                    'pl' => '<p>Tworzymy sklepy internetowe zaprojektowane z myślą o sprzedaży. Od WooCommerce po w pełni headless storefronty React — każde rozwiązanie dopasowujemy do Twojego katalogu produktów, modelu cenowego i ścieżki zakupowej klienta.</p><p>Nasze sklepy są szybkie, bezpieczne i zoptymalizowane pod konwersję — z uproszczonym checkoutem, filtrowaniem produktów i integracjami ze Stripe, PayPal i wiodącymi kurierami.</p>',
                    'pt' => '<p>Criamos lojas de comércio eletrónico desenhadas para vender. Do WooCommerce a storefronts React totalmente headless, adaptamos cada solução ao seu catálogo de produtos, modelo de preços e percurso do cliente.</p><p>As nossas lojas são rápidas, seguras e otimizadas para conversão — com checkouts simplificados, filtragem de produtos e integrações nativas com Stripe, PayPal e os principais transportadores.</p>',
                ],
                'features' => [
                    ['text_en' => 'WooCommerce or custom headless storefront',       'text_pl' => 'WooCommerce lub własny headless storefront',       'text_pt' => 'WooCommerce ou storefront headless personalizado'],
                    ['text_en' => 'Stripe & PayPal payment integration',              'text_pl' => 'Integracja płatności Stripe i PayPal',               'text_pt' => 'Integração de pagamentos Stripe e PayPal'],
                    ['text_en' => 'Product catalogue & inventory management',         'text_pl' => 'Katalog produktów i zarządzanie magazynem',           'text_pt' => 'Catálogo de produtos e gestão de inventário'],
                    ['text_en' => 'Abandoned cart recovery emails',                   'text_pl' => 'E-maile odzyskiwania porzuconych koszyków',           'text_pt' => 'E-mails de recuperação de carrinho abandonado'],
                    ['text_en' => 'Multi-currency & multi-language support',          'text_pl' => 'Obsługa wielu walut i języków',                       'text_pt' => 'Suporte a múltiplas moedas e idiomas'],
                    ['text_en' => 'Google Shopping & Meta Catalogue integration',     'text_pl' => 'Integracja z Google Shopping i Meta Catalogue',       'text_pt' => 'Integração com Google Shopping e Meta Catalogue'],
                ],
                'faq' => [
                    [
                        'q_en' => 'WooCommerce or custom — which is better for me?',
                        'q_pl' => 'WooCommerce czy custom — co jest lepsze dla mnie?',
                        'q_pt' => 'WooCommerce ou custom — qual é melhor para mim?',
                        'a_en' => 'WooCommerce suits most SME stores. Custom headless is recommended for 1000+ SKUs, complex pricing, or when performance is critical.',
                        'a_pl' => 'WooCommerce sprawdza się dla większości MŚP. Headless rekomendujemy przy 1000+ SKU, złożonym cenniku lub gdy kluczowa jest wydajność.',
                        'a_pt' => 'O WooCommerce serve a maioria das PME. O headless é recomendado para 1000+ SKUs, preços complexos ou quando a performance é crítica.',
                    ],
                    [
                        'q_en' => 'Do you handle product data migration?',
                        'q_pl' => 'Czy obsługujecie migrację danych produktów?',
                        'q_pt' => 'Fazem a migração de dados de produtos?',
                        'a_en' => 'Yes. We migrate products, categories, customer data, and order history from your existing platform.',
                        'a_pl' => 'Tak. Migrujemy produkty, kategorie, dane klientów i historię zamówień z Twojej obecnej platformy.',
                        'a_pt' => 'Sim. Migramos produtos, categorias, dados de clientes e histórico de encomendas da sua plataforma atual.',
                    ],
                ],
                'cta_label' => ['en' => 'Start Selling Online', 'pl' => 'Zacznij sprzedawać online', 'pt' => 'Comece a Vender Online'],
                'cta_url'   => '/contact',
                'meta_title' => [
                    'en' => 'E-Commerce Stores from £2,999 | Website Expert',
                    'pl' => 'Sklepy e-commerce od £2,999 | Website Expert',
                    'pt' => 'Lojas E-Commerce a partir de £2,999 | Website Expert',
                ],
                'meta_description' => [
                    'en' => 'Custom WooCommerce and headless e-commerce stores built to convert. Stripe, PayPal, multi-currency. From £2,999.',
                    'pl' => 'Sklepy WooCommerce i headless zbudowane z myślą o konwersji. Stripe, PayPal, wiele walut. Od £2,999.',
                    'pt' => 'Lojas WooCommerce e headless criadas para converter. Stripe, PayPal, multi-moeda. A partir de £2,999.',
                ],
                'icon'        => 'shopping-cart',
                'price_from'  => '£2,999',
                'link'        => '/services/ecommerce',
                'slug'        => 'ecommerce',
                'is_featured' => true,
                'is_active'   => true,
                'sort_order'  => 2,
            ],
            [
                'title'       => ['en' => 'Web Applications', 'pl' => 'Aplikacje internetowe', 'pt' => 'Aplicações Web'],
                'badge_text'  => ['en' => 'Bespoke Build', 'pl' => 'Dedykowane rozwiązanie', 'pt' => 'Solução à Medida'],
                'description' => [
                    'en' => 'Bespoke Laravel and React applications. Customer portals, SaaS platforms, booking systems.',
                    'pl' => 'Dedykowane aplikacje Laravel i React. Portale klientów, platformy SaaS, systemy rezerwacji.',
                    'pt' => 'Aplicações Laravel e React à medida. Portais de clientes, plataformas SaaS, sistemas de reservas.',
                ],
                'body' => [
                    'en' => '<p>Off-the-shelf software rarely fits perfectly. We design and build bespoke web applications using Laravel (backend) and React (frontend) that do exactly what your business needs — nothing more, nothing less.</p><p>Whether you need a customer portal, a SaaS product, an internal dashboard, or a complex booking system, our team can take it from idea to production.</p>',
                    'pl' => '<p>Gotowe oprogramowanie rzadko pasuje idealnie. Projektujemy i budujemy dedykowane aplikacje webowe w Laravel (backend) i React (frontend), które robią dokładnie to, czego potrzebuje Twój biznes.</p><p>Bez względu na to, czy potrzebujesz portalu klienta, produktu SaaS, wewnętrznego dashboardu czy zaawansowanego systemu rezerwacji — przeprowadzamy Cię od pomysłu do produkcji.</p>',
                    'pt' => '<p>O software standard raramente se ajusta perfeitamente. Desenhamos e criamos aplicações web à medida com Laravel (backend) e React (frontend) que fazem exatamente o que o seu negócio precisa.</p><p>Seja um portal de clientes, um produto SaaS, um dashboard interno ou um sistema de reservas complexo, a nossa equipa leva-o da ideia à produção.</p>',
                ],
                'features' => [
                    ['text_en' => 'Laravel 13 + React/TypeScript stack',                'text_pl' => 'Stack Laravel 13 + React/TypeScript',                    'text_pt' => 'Stack Laravel 13 + React/TypeScript'],
                    ['text_en' => 'Role-based access control (RBAC)',                   'text_pl' => 'Kontrola dostępu oparta na rolach (RBAC)',                 'text_pt' => 'Controlo de acesso baseado em funções (RBAC)'],
                    ['text_en' => 'REST API or GraphQL integration',                    'text_pl' => 'Integracja REST API lub GraphQL',                         'text_pt' => 'Integração REST API ou GraphQL'],
                    ['text_en' => 'Queue jobs, events & real-time notifications',       'text_pl' => 'Kolejki, eventy i powiadomienia real-time',               'text_pt' => 'Jobs, eventos e notificações em tempo real'],
                    ['text_en' => 'Multi-tenancy architecture (SaaS-ready)',            'text_pl' => 'Architektura multi-tenancy (gotowa na SaaS)',              'text_pt' => 'Arquitetura multi-tenant (pronta para SaaS)'],
                    ['text_en' => 'Automated testing & CI/CD pipeline setup',           'text_pl' => 'Testy automatyczne i konfiguracja CI/CD',                 'text_pt' => 'Testes automatizados e configuração de CI/CD'],
                ],
                'faq' => [
                    [
                        'q_en' => 'How do you estimate the cost of a web application?',
                        'q_pl' => 'Jak wyceniacie aplikację webową?',
                        'q_pt' => 'Como estimam o custo de uma aplicação web?',
                        'a_en' => 'We run a paid discovery phase (from £599) to define scope, architecture, and a fixed-price quote.',
                        'a_pl' => 'Prowadzimy płatną fazę discovery (od £599) w celu określenia zakresu, architektury i wyceny stałej ceny.',
                        'a_pt' => 'Realizamos uma fase de descoberta paga (a partir de £599) para definir o âmbito, a arquitetura e um orçamento a preço fixo.',
                    ],
                    [
                        'q_en' => 'Can you take over an existing application?',
                        'q_pl' => 'Czy możecie przejąć istniejącą aplikację?',
                        'q_pt' => 'Podem assumir uma aplicação existente?',
                        'a_en' => 'Yes. We conduct a code audit first, then propose a takeover or refactor plan depending on the current state of the codebase.',
                        'a_pl' => 'Tak. Najpierw przeprowadzamy audyt kodu, a następnie proponujemy plan przejęcia lub refaktoryzacji w zależności od stanu bazy kodu.',
                        'a_pt' => 'Sim. Realizamos primeiro uma auditoria de código, depois propõemos um plano de takeover ou refatorização consoante o estado atual do código.',
                    ],
                ],
                'cta_label' => ['en' => 'Discuss Your Project', 'pl' => 'Omów swój projekt', 'pt' => 'Fale Sobre o Seu Projeto'],
                'cta_url'   => '/contact',
                'meta_title' => [
                    'en' => 'Bespoke Web Applications | Laravel & React | Website Expert',
                    'pl' => 'Dedykowane aplikacje webowe | Laravel & React | Website Expert',
                    'pt' => 'Aplicações Web à Medida | Laravel & React | Website Expert',
                ],
                'meta_description' => [
                    'en' => 'Custom Laravel & React web applications: SaaS platforms, customer portals, booking systems. From £5,999.',
                    'pl' => 'Dedykowane aplikacje Laravel & React: platformy SaaS, portale klientów, systemy rezerwacji. Od £5,999.',
                    'pt' => 'Aplicações web Laravel & React à medida: plataformas SaaS, portais de clientes, sistemas de reservas. A partir de £5,999.',
                ],
                'icon'        => 'code',
                'price_from'  => '£5,999',
                'link'        => '/services/web-applications',
                'slug'        => 'web-applications',
                'is_featured' => true,
                'is_active'   => true,
                'sort_order'  => 3,
            ],
            [
                'title'       => ['en' => 'SEO & Digital Marketing', 'pl' => 'SEO i Marketing Cyfrowy', 'pt' => 'SEO e Marketing Digital'],
                'badge_text'  => ['en' => 'Long-Term Growth', 'pl' => 'Długoterminowy wzrost', 'pt' => 'Crescimento a Longo Prazo'],
                'description' => [
                    'en' => 'Rank higher, attract more visitors, and convert them into paying customers.',
                    'pl' => 'Zaistniej w Google. Audyty SEO, optymalizacja on-page i strategia contentu.',
                    'pt' => 'Posicione-se mais alto, atraia mais visitantes e converta-os em clientes pagantes.',
                ],
                'body' => [
                    'en' => '<p>Search engine optimisation is the most cost-effective long-term marketing channel. We combine technical SEO, on-page optimisation, and a content strategy to grow your organic traffic month on month.</p><p>Our work starts with a deep technical audit — crawl errors, Core Web Vitals, schema markup, backlink profile — and translates into a prioritised action plan with measurable KPIs.</p>',
                    'pl' => '<p>SEO to najbardziej opłacalny długoterminowy kanał marketingowy. Łączymy techniczne SEO, optymalizację on-page i strategię treści, aby każdego miesiąca zwiększać ruch organiczny.</p><p>Zaczynamy od głębokiego audytu technicznego — błędy crawlowania, Core Web Vitals, markup schematu, profil linków zwrotnych — i przekładamy to na priorytetowy plan działania z mierzalnymi KPI.</p>',
                    'pt' => '<p>A otimização para motores de busca é o canal de marketing de longo prazo mais rentável. Combinamos SEO técnico, otimização on-page e estratégia de conteúdo para crescer o seu tráfego orgânico mês após mês.</p><p>O nosso trabalho começa com uma auditoria técnica profunda — erros de crawl, Core Web Vitals, schema markup, perfil de backlinks — e traduz-se num plano de ação priorizado com KPIs mensuráveis.</p>',
                ],
                'features' => [
                    ['text_en' => 'Full technical SEO audit & fix list',                'text_pl' => 'Pełny audyt techniczny SEO i lista poprawek',              'text_pt' => 'Auditoria técnica SEO completa e lista de correções'],
                    ['text_en' => 'Keyword research & content strategy',               'text_pl' => 'Badanie słów kluczowych i strategia treści',               'text_pt' => 'Pesquisa de palavras-chave e estratégia de conteúdo'],
                    ['text_en' => 'On-page optimisation (titles, headings, schema)',    'text_pl' => 'Optymalizacja on-page (tytuły, nagłówki, schema)',          'text_pt' => 'Otimização on-page (títulos, headings, schema)'],
                    ['text_en' => 'Monthly performance reports with GA4 & GSC data',   'text_pl' => 'Miesięczne raporty z danymi GA4 i GSC',                    'text_pt' => 'Relatórios mensais de desempenho com dados GA4 e GSC'],
                    ['text_en' => 'Local SEO & Google Business Profile optimisation',  'text_pl' => 'SEO lokalne i optymalizacja Google Business Profile',      'text_pt' => 'SEO local e otimização do Google Business Profile'],
                    ['text_en' => 'Link building outreach',                             'text_pl' => 'Link building i outreach',                                 'text_pt' => 'Link building e outreach'],
                ],
                'faq' => [
                    [
                        'q_en' => 'How long before I see results from SEO?',
                        'q_pl' => 'Kiedy zobaczę efekty SEO?',
                        'q_pt' => 'Quanto tempo até ver resultados de SEO?',
                        'a_en' => 'Most clients see measurable improvements in 3–6 months. Competitive niches may take 6–12 months for top-3 rankings.',
                        'a_pl' => 'Większość klientów widzi mierzalne efekty w ciągu 3–6 miesięcy. Konkurencyjne nisze mogą wymagać 6–12 miesięcy na TOP 3.',
                        'a_pt' => 'A maioria dos clientes vê melhorias mensuráveis em 3 a 6 meses. Nichos competitivos podem demorar 6 a 12 meses para o top 3.',
                    ],
                    [
                        'q_en' => 'Do you offer one-off SEO audits?',
                        'q_pl' => 'Czy oferujecie jednorazowe audyty SEO?',
                        'q_pt' => 'Oferecem auditorias SEO pontuais?',
                        'a_en' => 'Yes. A standalone technical SEO audit starts from £299 and includes a prioritised fix list and 1-hour consultation.',
                        'a_pl' => 'Tak. Jednorazowy audyt techniczny SEO zaczyna się od £299 i obejmuje priorytetową listę poprawek oraz 1-godzinną konsultację.',
                        'a_pt' => 'Sim. Uma auditoria técnica SEO autónoma começa a partir de £299 e inclui uma lista de correções prioritizadas e 1 hora de consulta.',
                    ],
                ],
                'cta_label' => ['en' => 'Get an SEO Audit', 'pl' => 'Zamów audyt SEO', 'pt' => 'Obter Auditoria SEO'],
                'cta_url'   => '/contact',
                'meta_title' => [
                    'en' => 'SEO & Digital Marketing Services | Website Expert',
                    'pl' => 'SEO i Marketing Cyfrowy | Website Expert',
                    'pt' => 'Serviços de SEO e Marketing Digital | Website Expert',
                ],
                'meta_description' => [
                    'en' => 'Technical SEO audits, on-page optimisation, keyword strategy & monthly reporting. Grow organic traffic from £499/mo.',
                    'pl' => 'Audyty techniczne SEO, optymalizacja on-page, strategia słów kluczowych i miesięczne raporty. Wzrost ruchu organicznego od £499/mc.',
                    'pt' => 'Auditorias SEO técnicas, otimização on-page, estratégia de palavras-chave e relatórios mensais. A partir de £499/mês.',
                ],
                'icon'        => 'search',
                'price_from'  => '£499/mo',
                'link'        => '/services/seo',
                'slug'        => 'seo',
                'is_featured' => true,
                'is_active'   => true,
                'sort_order'  => 4,
            ],
            [
                'title'       => ['en' => 'Google Ads (PPC)', 'pl' => 'Google Ads (PPC)', 'pt' => 'Google Ads (PPC)'],
                'badge_text'  => ['en' => 'Instant Traffic', 'pl' => 'Natychmiastowy ruch', 'pt' => 'Tráfego Imediato'],
                'description' => [
                    'en' => 'Targeted pay-per-click campaigns that deliver measurable ROI from day one.',
                    'pl' => 'Kampanie płatne z realnym ROI – konfiguracja, optymalizacja i raportowanie.',
                    'pt' => 'Campanhas pagas por clique com ROI mensurável desde o primeiro dia.',
                ],
                'body' => [
                    'en' => '<p>Google Ads puts your business in front of people who are actively searching for what you offer. We set up, manage, and continuously optimise Search, Shopping, and Performance Max campaigns to deliver the lowest cost-per-acquisition possible.</p><p>Every campaign is backed by conversion tracking, A/B tested ad copy, and monthly reporting so you always know your ROI.</p>',
                    'pl' => '<p>Google Ads stawia Twój biznes przed ludźmi, którzy aktywnie szukają tego, co oferujesz. Konfigurujemy, zarządzamy i ciągle optymalizujemy kampanie Search, Shopping i Performance Max, aby osiągnąć najniższy możliwy koszt konwersji.</p><p>Każda kampania jest oparta na śledzeniu konwersji, testach A/B treści reklam i miesięcznych raportach, dzięki czemu zawsze znasz swój ROI.</p>',
                    'pt' => '<p>O Google Ads coloca o seu negócio à frente de pessoas que estão ativamente à procura do que oferece. Configuramos, gerimos e otimizamos continuamente campanhas Search, Shopping e Performance Max para entregar o menor custo por aquisição possível.</p><p>Cada campanha é suportada por rastreamento de conversões, textos de anúncios testados A/B e relatórios mensais para que saiba sempre o seu ROI.</p>',
                ],
                'features' => [
                    ['text_en' => 'Google Search, Shopping & Performance Max',         'text_pl' => 'Google Search, Shopping i Performance Max',              'text_pt' => 'Google Search, Shopping e Performance Max'],
                    ['text_en' => 'Conversion tracking & Google Tag Manager setup',    'text_pl' => 'Śledzenie konwersji i konfiguracja GTM',                  'text_pt' => 'Rastreamento de conversões e configuração do GTM'],
                    ['text_en' => 'Keyword research & negative keyword management',    'text_pl' => 'Badanie słów kluczowych i zarządzanie wykluczeniami',      'text_pt' => 'Pesquisa de palavras-chave e gestão de palavras negativas'],
                    ['text_en' => 'Ad copy A/B testing',                               'text_pl' => 'Testy A/B treści reklam',                                 'text_pt' => 'Testes A/B de textos de anúncios'],
                    ['text_en' => 'Monthly performance reports with ROI breakdown',    'text_pl' => 'Miesięczne raporty z podziałem na ROI',                   'text_pt' => 'Relatórios mensais com breakdown de ROI'],
                    ['text_en' => 'Remarketing & audience targeting',                  'text_pl' => 'Remarketing i targetowanie grup odbiorców',               'text_pt' => 'Remarketing e segmentação de audiências'],
                ],
                'faq' => [
                    [
                        'q_en' => 'What budget do I need for Google Ads?',
                        'q_pl' => 'Jakiego budżetu potrzebuję na Google Ads?',
                        'q_pt' => 'Que orçamento preciso para o Google Ads?',
                        'a_en' => 'We recommend a minimum ad spend of £500/mo. Our management fee starts at £399/mo and is separate from ad spend.',
                        'a_pl' => 'Zalecamy minimalny budżet reklamowy £500/mc. Nasze wynagrodzenie za zarządzanie zaczyna się od £399/mc i jest oddzielne od budżetu.',
                        'a_pt' => 'Recomendamos um investimento mínimo em anúncios de £500/mês. A nossa taxa de gestão começa a partir de £399/mês e é separada do investimento.',
                    ],
                    [
                        'q_en' => 'Can you manage an existing Google Ads account?',
                        'q_pl' => 'Czy możecie zarządzać istniejącym kontem Google Ads?',
                        'q_pt' => 'Podem gerir uma conta Google Ads existente?',
                        'a_en' => 'Yes. We start with a free audit of your existing account and identify quick wins before taking over management.',
                        'a_pl' => 'Tak. Zaczynamy od bezpłatnego audytu Twojego konta i identyfikujemy szybkie wygrane przed przejęciem zarządzania.',
                        'a_pt' => 'Sim. Começamos com uma auditoria gratuita da sua conta existente e identificamos ganhos rápidos antes de assumir a gestão.',
                    ],
                ],
                'cta_label' => ['en' => 'Get a Free Audit', 'pl' => 'Pobierz bezpłatny audyt', 'pt' => 'Obter Auditoria Gratuita'],
                'cta_url'   => '/contact',
                'meta_title' => [
                    'en' => 'Google Ads Management (PPC) | Website Expert',
                    'pl' => 'Zarządzanie Google Ads (PPC) | Website Expert',
                    'pt' => 'Gestão de Google Ads (PPC) | Website Expert',
                ],
                'meta_description' => [
                    'en' => 'Expert Google Ads management: Search, Shopping & Performance Max. Conversion tracking, A/B testing. From £399/mo.',
                    'pl' => 'Profesjonalne zarządzanie Google Ads: Search, Shopping, Performance Max. Śledzenie konwersji, testy A/B. Od £399/mc.',
                    'pt' => 'Gestão especializada de Google Ads: Search, Shopping e Performance Max. Rastreamento de conversões, testes A/B. A partir de £399/mês.',
                ],
                'icon'        => 'bar-chart',
                'price_from'  => '£399/mo',
                'link'        => '/services/google-ads',
                'slug'        => 'google-ads',
                'is_featured' => true,
                'is_active'   => true,
                'sort_order'  => 5,
            ],
            [
                'title'       => ['en' => 'Meta / Pixel Ads', 'pl' => 'Reklamy Meta / Pixel', 'pt' => 'Anúncios Meta / Pixel'],
                'badge_text'  => ['en' => 'Social Reach', 'pl' => 'Zasięg social media', 'pt' => 'Alcance Social'],
                'description' => [
                    'en' => 'Facebook & Instagram campaigns with Pixel tracking, retargeting and lookalike audiences.',
                    'pl' => 'Kampanie Facebook & Instagram z Pixelem, remarketingiem i grupami lookalike.',
                    'pt' => 'Campanhas no Facebook & Instagram com rastreamento Pixel, remarketing e públicos semelhantes.',
                ],
                'body' => [
                    'en' => '<p>Meta platforms reach over 3 billion active users. We design and manage Facebook and Instagram advertising campaigns that build awareness, drive traffic, and generate leads or sales — all tracked to the last click via the Meta Pixel and Conversions API.</p><p>From carousel ads to Reels and lead generation forms, we create creative that stops the scroll and copy that converts.</p>',
                    'pl' => '<p>Platformy Meta docierają do ponad 3 miliardów aktywnych użytkowników. Projektujemy i zarządzamy kampaniami reklamowymi na Facebooku i Instagramie, które budują świadomość, generują ruch i pozyskują leady lub sprzedaż — wszystko śledzone do ostatniego kliknięcia przez Meta Pixel i Conversions API.</p><p>Od reklam karuzelowych po Reels i formularze lead generation — tworzymy kreacje, które zatrzymują scroll, i teksty, które konwertują.</p>',
                    'pt' => '<p>As plataformas Meta alcançam mais de 3 mil milhões de utilizadores ativos. Desenhamos e gerimos campanhas publicitárias no Facebook e Instagram que constroem awareness, geram tráfego e leads ou vendas — tudo rastreado até ao último clique via Meta Pixel e Conversions API.</p><p>De anúncios carrossel a Reels e formulários de geração de leads, criamos criativos que param o scroll e copy que converte.</p>',
                ],
                'features' => [
                    ['text_en' => 'Meta Pixel & Conversions API setup',               'text_pl' => 'Konfiguracja Meta Pixel i Conversions API',               'text_pt' => 'Configuração do Meta Pixel e Conversions API'],
                    ['text_en' => 'Audience building: custom, lookalike & interest',   'text_pl' => 'Budowanie grup: custom, lookalike i zainteresowania',      'text_pt' => 'Construção de audiências: custom, lookalike e interesses'],
                    ['text_en' => 'Carousel, video, Reels & lead form campaigns',      'text_pl' => 'Kampanie karuzelowe, wideo, Reels i lead form',            'text_pt' => 'Campanhas de carrossel, vídeo, Reels e formulários de leads'],
                    ['text_en' => 'Retargeting & dynamic product ads',                 'text_pl' => 'Retargeting i dynamiczne reklamy produktowe',              'text_pt' => 'Remarketing e anúncios dinâmicos de produtos'],
                    ['text_en' => 'Creative copywriting & image/video sourcing',       'text_pl' => 'Copywriting i pozyskiwanie grafik/wideo',                  'text_pt' => 'Copywriting e sourcing de imagens/vídeos'],
                    ['text_en' => 'Monthly reporting with ROAS & CPA metrics',         'text_pl' => 'Miesięczne raporty z ROAS i CPA',                         'text_pt' => 'Relatórios mensais com métricas ROAS e CPA'],
                ],
                'faq' => [
                    [
                        'q_en' => 'What ad spend do you recommend for Meta Ads?',
                        'q_pl' => 'Jaki budżet reklamowy zalecacie na Meta Ads?',
                        'q_pt' => 'Que investimento recomendam para Meta Ads?',
                        'a_en' => 'We recommend a minimum of £300/mo ad spend to gather enough data for optimisation. Our management fee starts at £349/mo.',
                        'a_pl' => 'Zalecamy minimum £300/mc budżetu reklamowego, aby zebrać wystarczające dane do optymalizacji. Opłata za zarządzanie zaczyna się od £349/mc.',
                        'a_pt' => 'Recomendamos um mínimo de £300/mês em anúncios para recolher dados suficientes para otimização. A nossa taxa de gestão começa a partir de £349/mês.',
                    ],
                ],
                'cta_label' => ['en' => 'Launch Your Campaign', 'pl' => 'Uruchom kampanię', 'pt' => 'Lançar a Sua Campanha'],
                'cta_url'   => '/contact',
                'meta_title' => [
                    'en' => 'Meta Ads (Facebook & Instagram) Management | Website Expert',
                    'pl' => 'Zarządzanie Meta Ads (Facebook & Instagram) | Website Expert',
                    'pt' => 'Gestão de Meta Ads (Facebook & Instagram) | Website Expert',
                ],
                'meta_description' => [
                    'en' => 'Facebook & Instagram ad campaigns with Pixel, retargeting and lookalike audiences. Managed from £349/mo.',
                    'pl' => 'Kampanie Facebook & Instagram z Pixelem, remarketingiem i grupami lookalike. Zarządzanie od £349/mc.',
                    'pt' => 'Campanhas de anúncios Facebook & Instagram com Pixel, remarketing e públicos semelhantes. Gestão a partir de £349/mês.',
                ],
                'icon'        => 'zap',
                'price_from'  => '£349/mo',
                'link'        => '/services/meta-ads',
                'slug'        => 'meta-ads',
                'is_featured' => true,
                'is_active'   => true,
                'sort_order'  => 6,
            ],
            [
                'title'       => ['en' => 'Content Creation', 'pl' => 'Tworzenie treści', 'pt' => 'Criação de Conteúdo'],
                'badge_text'  => ['en' => 'Multilingual', 'pl' => 'Wielojęzyczne', 'pt' => 'Multilingue'],
                'description' => [
                    'en' => 'Copywriting, blog articles, product descriptions and social media content in EN, PL and PT.',
                    'pl' => 'Copywriting, artykuły blogowe, opisy produktów i treści social media w PL, EN i PT.',
                    'pt' => 'Copywriting, artigos de blog, descrições de produtos e conteúdo para redes sociais em PT, EN e PL.',
                ],
                'body' => [
                    'en' => '<p>Great content drives organic traffic, builds authority, and converts browsers into buyers. Our bilingual and trilingual writers create content that resonates with your audience in English, Polish, and Portuguese.</p><p>From landing page copy and blog posts to product descriptions and social media calendars — we produce content that ranks and reads well.</p>',
                    'pl' => '<p>Dobra treść napędza ruch organiczny, buduje autorytet i przekształca odwiedzających w klientów. Nasi dwu- i trójjęzyczni autorzy tworzą treści, które trafiają do Twojej grupy docelowej po angielsku, polsku i portugalsku.</p><p>Od tekstów na landing pages i artykułów blogowych po opisy produktów i kalendarze social media — tworzymy treści, które rankują i dobrze się czytają.</p>',
                    'pt' => '<p>O bom conteúdo impulsiona o tráfego orgânico, constrói autoridade e converte visitantes em compradores. Os nossos escritores bi e trilingues criam conteúdo que ressoa com a sua audiência em inglês, polaco e português.</p><p>De copy para landing pages e artigos de blog a descrições de produtos e calendários de redes sociais — produzimos conteúdo que posiciona e se lê bem.</p>',
                ],
                'features' => [
                    ['text_en' => 'SEO-optimised blog articles & landing pages',       'text_pl' => 'Artykuły blogowe i landing pages zoptymalizowane pod SEO', 'text_pt' => 'Artigos de blog e landing pages otimizados para SEO'],
                    ['text_en' => 'Product descriptions for e-commerce',               'text_pl' => 'Opisy produktów dla e-commerce',                           'text_pt' => 'Descrições de produtos para e-commerce'],
                    ['text_en' => 'Social media caption & content calendar',           'text_pl' => 'Podpisy social media i kalendarz treści',                  'text_pt' => 'Legendas de redes sociais e calendário de conteúdo'],
                    ['text_en' => 'Email newsletters & drip sequences',                'text_pl' => 'Newslettery i sekwencje e-mail drip',                      'text_pt' => 'Newsletters e sequências de e-mail drip'],
                    ['text_en' => 'Content in English, Polish & Portuguese',           'text_pl' => 'Treści po angielsku, polsku i portugalsku',                'text_pt' => 'Conteúdo em inglês, polaco e português'],
                    ['text_en' => 'Tone-of-voice guidelines included',                 'text_pl' => 'Wytyczne tone of voice w zestawie',                        'text_pt' => 'Diretrizes de tom de voz incluídas'],
                ],
                'faq' => [
                    [
                        'q_en' => 'How many pieces of content do I get per month?',
                        'q_pl' => 'Ile treści otrzymuję miesięcznie?',
                        'q_pt' => 'Quantas peças de conteúdo recebo por mês?',
                        'a_en' => 'Our starter plan (£199/mo) includes 4 blog posts or 8 social media captions. Custom volumes are available.',
                        'a_pl' => 'Nasz plan startowy (£199/mc) obejmuje 4 artykuły blogowe lub 8 podpisów social media. Dostępne są niestandardowe wolumeny.',
                        'a_pt' => 'O nosso plano inicial (£199/mês) inclui 4 artigos de blog ou 8 legendas para redes sociais. Volumes personalizados disponíveis.',
                    ],
                ],
                'cta_label' => ['en' => 'Start Creating Content', 'pl' => 'Zacznij tworzyć treści', 'pt' => 'Começar a Criar Conteúdo'],
                'cta_url'   => '/contact',
                'meta_title' => [
                    'en' => 'Content Creation Services in EN, PL & PT | Website Expert',
                    'pl' => 'Tworzenie treści w EN, PL i PT | Website Expert',
                    'pt' => 'Serviços de Criação de Conteúdo em EN, PL e PT | Website Expert',
                ],
                'meta_description' => [
                    'en' => 'SEO-optimised blog posts, landing pages, product descriptions and social media content in English, Polish and Portuguese. From £199/mo.',
                    'pl' => 'Artykuły blogowe, landing pages, opisy produktów i treści social media zoptymalizowane pod SEO w EN, PL i PT. Od £199/mc.',
                    'pt' => 'Artigos de blog, landing pages, descrições de produtos e conteúdo social media otimizados para SEO em EN, PL e PT. A partir de £199/mês.',
                ],
                'icon'        => 'file-text',
                'price_from'  => '£199/mo',
                'link'        => '/services/content',
                'slug'        => 'content',
                'is_featured' => true,
                'is_active'   => true,
                'sort_order'  => 7,
            ],
            [
                'title'       => ['en' => 'Security & Performance Audits', 'pl' => 'Audyty bezpieczeństwa i wydajności', 'pt' => 'Auditorias de Segurança e Desempenho'],
                'badge_text'  => ['en' => 'One-Off Service', 'pl' => 'Jednorazowa usługa', 'pt' => 'Serviço Pontual'],
                'description' => [
                    'en' => 'In-depth security testing, Core Web Vitals optimisation and actionable performance reports.',
                    'pl' => 'Głęboka analiza bezpieczeństwa, optymalizacja Core Web Vitals i raporty z rekomendacjami.',
                    'pt' => 'Testes de segurança aprofundados, otimização de Core Web Vitals e relatórios de desempenho.',
                ],
                'body' => [
                    'en' => '<p>A slow or insecure website loses customers and search rankings. Our audits give you a clear, prioritised picture of every vulnerability and performance bottleneck — and tell you exactly how to fix them.</p><p>We test against OWASP Top 10 vulnerabilities, check Core Web Vitals (LCP, CLS, INP), analyse your server configuration, and review your dependency stack for known CVEs.</p>',
                    'pl' => '<p>Wolna lub niezabezpieczona strona traci klientów i pozycje w wyszukiwarce. Nasze audyty dają Ci jasny, priorytetowy obraz każdej luki i wąskiego gardła wydajności — i mówią Ci dokładnie, jak je naprawić.</p><p>Testujemy pod kątem luk OWASP Top 10, sprawdzamy Core Web Vitals (LCP, CLS, INP), analizujemy konfigurację serwera i przeglądamy stos zależności pod kątem znanych CVE.</p>',
                    'pt' => '<p>Um site lento ou inseguro perde clientes e posições de pesquisa. As nossas auditorias dão-lhe uma imagem clara e priorizada de cada vulnerabilidade e gargalo de desempenho — e dizem-lhe exatamente como os corrigir.</p><p>Testamos contra vulnerabilidades OWASP Top 10, verificamos Core Web Vitals (LCP, CLS, INP), analisamos a configuração do servidor e revemos o stack de dependências para CVEs conhecidos.</p>',
                ],
                'features' => [
                    ['text_en' => 'OWASP Top 10 security vulnerability scan',          'text_pl' => 'Skan luk bezpieczeństwa OWASP Top 10',                    'text_pt' => 'Scan de vulnerabilidades de segurança OWASP Top 10'],
                    ['text_en' => 'Core Web Vitals (LCP, CLS, INP) analysis',          'text_pl' => 'Analiza Core Web Vitals (LCP, CLS, INP)',                  'text_pt' => 'Análise de Core Web Vitals (LCP, CLS, INP)'],
                    ['text_en' => 'Server configuration & SSL review',                 'text_pl' => 'Przegląd konfiguracji serwera i SSL',                      'text_pt' => 'Revisão da configuração do servidor e SSL'],
                    ['text_en' => 'Dependency & CVE audit',                            'text_pl' => 'Audyt zależności i CVE',                                   'text_pt' => 'Auditoria de dependências e CVE'],
                    ['text_en' => 'Prioritised fix list with effort estimates',        'text_pl' => 'Priorytetowa lista poprawek z szacunkiem nakładu pracy',   'text_pt' => 'Lista de correções priorizadas com estimativas de esforço'],
                    ['text_en' => '1-hour debrief call included',                      'text_pl' => '1-godzinna rozmowa podsumowująca w zestawie',             'text_pt' => '1 hora de chamada de debriefing incluída'],
                ],
                'faq' => [
                    [
                        'q_en' => 'How long does an audit take?',
                        'q_pl' => 'Ile trwa audyt?',
                        'q_pt' => 'Quanto tempo demora uma auditoria?',
                        'a_en' => 'A full security and performance audit typically takes 5–7 business days. You receive a PDF report and a 1-hour debrief call.',
                        'a_pl' => 'Pełny audyt bezpieczeństwa i wydajności trwa zazwyczaj 5–7 dni roboczych. Otrzymujesz raport PDF i 1-godzinną rozmowę podsumowującą.',
                        'a_pt' => 'Uma auditoria completa de segurança e desempenho demora normalmente 5 a 7 dias úteis. Recebe um relatório PDF e uma chamada de debriefing de 1 hora.',
                    ],
                ],
                'cta_label' => ['en' => 'Book an Audit', 'pl' => 'Zamów audyt', 'pt' => 'Agendar Auditoria'],
                'cta_url'   => '/contact',
                'meta_title' => [
                    'en' => 'Website Security & Performance Audits | Website Expert',
                    'pl' => 'Audyty bezpieczeństwa i wydajności strony | Website Expert',
                    'pt' => 'Auditorias de Segurança e Desempenho de Website | Website Expert',
                ],
                'meta_description' => [
                    'en' => 'OWASP security scans, Core Web Vitals analysis and actionable fix reports. Protect and speed up your website from £299.',
                    'pl' => 'Skany bezpieczeństwa OWASP, analiza Core Web Vitals i raporty z poprawkami. Zabezpiecz i przyspiesz swoją stronę od £299.',
                    'pt' => 'Scans de segurança OWASP, análise de Core Web Vitals e relatórios de correções. Proteja e acelere o seu website a partir de £299.',
                ],
                'icon'        => 'shield',
                'price_from'  => '£299',
                'link'        => '/services/audits',
                'slug'        => 'audits',
                'is_featured' => true,
                'is_active'   => true,
                'sort_order'  => 8,
            ],
            [
                'title'       => ['en' => 'Website Maintenance', 'pl' => 'Opieka nad stroną', 'pt' => 'Manutenção de Website'],
                'badge_text'  => ['en' => 'Monthly Plan', 'pl' => 'Plan miesięczny', 'pt' => 'Plano Mensal'],
                'description' => [
                    'en' => 'Keep your site fast, secure, and up to date with our monthly care plans.',
                    'pl' => 'Szybki hosting z SSL, backupami i opieką techniczną w pakiecie.',
                    'pt' => 'Manter o seu site rápido, seguro e atualizado com os nossos planos de manutenção mensais.',
                ],
                'body' => [
                    'en' => '<p>Your website is not a one-off project — it needs ongoing attention to stay fast, secure, and functional. Our maintenance plans handle all the technical housekeeping so you can focus on your business.</p><p>We update plugins, themes, and core software, monitor uptime 24/7, run weekly backups, and resolve any issues that arise — all covered under a flat monthly fee.</p>',
                    'pl' => '<p>Twoja strona to nie jednorazowy projekt — wymaga ciągłej uwagi, aby pozostawać szybką, bezpieczną i funkcjonalną. Nasze plany opieki zajmują się całą techniczną obsługą, abyś mógł skupić się na swoim biznesie.</p><p>Aktualizujemy wtyczki, motywy i core software, monitorujemy dostępność 24/7, robimy tygodniowe backupy i rozwiązujemy wszelkie problemy — wszystko w ramach stałej miesięcznej opłaty.</p>',
                    'pt' => '<p>O seu website não é um projeto único — precisa de atenção contínua para se manter rápido, seguro e funcional. Os nossos planos de manutenção tratam de toda a gestão técnica para que se possa focar no seu negócio.</p><p>Atualizamos plugins, temas e software base, monitorizamos o uptime 24/7, fazemos backups semanais e resolvemos quaisquer problemas que surjam — tudo incluído numa taxa mensal fixa.</p>',
                ],
                'features' => [
                    ['text_en' => 'Plugin, theme & core software updates',             'text_pl' => 'Aktualizacje wtyczek, motywów i core software',             'text_pt' => 'Atualizações de plugins, temas e software base'],
                    ['text_en' => '24/7 uptime monitoring & instant alerts',           'text_pl' => 'Monitoring dostępności 24/7 i natychmiastowe alerty',       'text_pt' => 'Monitorização de uptime 24/7 e alertas instantâneos'],
                    ['text_en' => 'Weekly off-site backups with 30-day retention',     'text_pl' => 'Tygodniowe backupy off-site z 30-dniową retencją',          'text_pt' => 'Backups off-site semanais com retenção de 30 dias'],
                    ['text_en' => 'Monthly performance & security report',             'text_pl' => 'Miesięczny raport wydajności i bezpieczeństwa',             'text_pt' => 'Relatório mensal de desempenho e segurança'],
                    ['text_en' => 'Priority bug fixing (2-hour response SLA)',         'text_pl' => 'Priorytetowe naprawianie błędów (SLA 2h odpowiedzi)',       'text_pt' => 'Correção prioritária de bugs (SLA de resposta de 2h)'],
                    ['text_en' => 'SSL renewal & DNS management',                      'text_pl' => 'Odnowienie SSL i zarządzanie DNS',                         'text_pt' => 'Renovação SSL e gestão de DNS'],
                ],
                'faq' => [
                    [
                        'q_en' => 'What happens if something breaks outside office hours?',
                        'q_pl' => 'Co się dzieje, gdy coś się psuje poza godzinami pracy?',
                        'q_pt' => 'O que acontece se algo falhar fora do horário de trabalho?',
                        'a_en' => 'Our uptime monitoring alerts us immediately. Critical fixes are addressed within 2 hours on our Pro plan, 24/7.',
                        'a_pl' => 'Nasz monitoring dostępności natychmiast nas alarmuje. Krytyczne naprawy są realizowane w ciągu 2 godzin w naszym planie Pro, 24/7.',
                        'a_pt' => 'A nossa monitorização de uptime alerta-nos imediatamente. As correções críticas são tratadas em 2 horas no nosso plano Pro, 24/7.',
                    ],
                    [
                        'q_en' => 'Is hosting included in the maintenance plan?',
                        'q_pl' => 'Czy hosting jest wliczony w plan opieki?',
                        'q_pt' => 'O alojamento está incluído no plano de manutenção?',
                        'a_en' => 'Managed hosting can be added from £29/mo. We support all major hosts and can migrate your site if needed.',
                        'a_pl' => 'Zarządzany hosting można dodać od £29/mc. Obsługujemy wszystkich głównych hostingodawców i możemy migrować Twoją stronę w razie potrzeby.',
                        'a_pt' => 'O alojamento gerido pode ser adicionado a partir de £29/mês. Suportamos todos os principais alojamentos e podemos migrar o seu site se necessário.',
                    ],
                ],
                'cta_label' => ['en' => 'Get a Care Plan', 'pl' => 'Wybierz plan opieki', 'pt' => 'Obter um Plano de Manutenção'],
                'cta_url'   => '/contact',
                'meta_title' => [
                    'en' => 'Website Maintenance Plans | Website Expert',
                    'pl' => 'Plany opieki nad stroną | Website Expert',
                    'pt' => 'Planos de Manutenção de Website | Website Expert',
                ],
                'meta_description' => [
                    'en' => 'Keep your site fast, secure and up to date. Updates, backups, 24/7 uptime monitoring and priority support. From £149/mo.',
                    'pl' => 'Utrzymaj stronę szybką, bezpieczną i aktualną. Aktualizacje, backupy, monitoring 24/7 i wsparcie priorytetowe. Od £149/mc.',
                    'pt' => 'Mantenha o seu site rápido, seguro e atualizado. Atualizações, backups, monitorização 24/7 e suporte prioritário. A partir de £149/mês.',
                ],
                'icon'        => 'settings',
                'price_from'  => '£149/mo',
                'link'        => '/services/maintenance',
                'slug'        => 'maintenance',
                'is_featured' => true,
                'is_active'   => true,
                'sort_order'  => 9,
            ],
        ];

        foreach ($items as $data) {
            ServiceItem::updateOrCreate(
                ['slug' => $data['slug']],
                $data
            );
        }
    }
}
