<?php

namespace Database\Seeders;

use App\Models\SiteSection;
use Illuminate\Database\Seeder;

class SiteSectionSeeder extends Seeder
{
    public function run(): void
    {
        $sections = [
            // -------------------------------------------------------
            // Hero Section
            // -------------------------------------------------------
            [
                'key'         => 'hero',
                'label'       => 'Hero Section',
                'title'       => ['en' => 'We Build Websites That Win Clients',       'pl' => 'Tworzymy strony internetowe, które zdobywają klientów',          'pt' => 'Criamos Websites Que Conquistam Clientes'],
                'subtitle'    => ['en' => 'Bespoke web design and development for UK businesses. From stunning brochure sites to powerful web applications — built to perform, built to last.',
                                  'pl' => 'Dedykowane projektowanie i tworzenie stron dla firm z UK. Od efektownych stron wizytówkowych po rozbudowane aplikacje internetowe — zbudowane, by działać i trwać.',
                                  'pt' => 'Design e desenvolvimento web à medida para empresas do Reino Unido. De sites institucionais a aplicações web poderosas — construídos para durar e converter.'],
                'body'        => null,
                'button_text' => ['en' => 'Get a Free Quote', 'pl' => 'Darmowa wycena', 'pt' => 'Orçamento Gratuito'],
                'button_url'  => '#calculator',
                'image_path'  => null,
                'extra'       => [
                    'badge_text_en'                => '5-star rated on Google',
                    'badge_text_pl'                => 'Oceny 5 gwiazdek w Google',
                    'badge_text_pt'                => 'Classificação 5 estrelas no Google',
                    'secondary_button_text_en'     => 'View Our Work',
                    'secondary_button_text_pl'     => 'Zobacz nasze realizacje',
                    'secondary_button_text_pt'     => 'Ver o Nosso Trabalho',
                    'secondary_button_url'         => '#portfolio',
                    'scroll_label_en'              => 'Scroll',
                    'scroll_label_pl'              => 'Przewiń',
                    'scroll_label_pt'              => 'Rolar',
                    'mockup_domain_en'             => 'yourcompany.co.uk',
                    'mockup_domain_pl'             => 'twojafirma.pl',
                    'mockup_domain_pt'             => 'suaempresa.pt',
                    'mockup_timeline_label_en'     => 'Delivery time',
                    'mockup_timeline_label_pl'     => 'Czas realizacji',
                    'mockup_timeline_label_pt'     => 'Tempo de entrega',
                    'mockup_timeline_value_en'     => 'from 2 weeks',
                    'mockup_timeline_value_pl'     => 'od 2 tygodni',
                    'mockup_timeline_value_pt'     => 'a partir de 2 semanas',
                    'stats'                        => [
                        ['value' => '200+', 'label_en' => 'Websites Delivered',  'label_pl' => 'Projektów ukończonych',  'label_pt' => 'Websites Entregues'],
                        ['value' => '98%',  'label_en' => 'Client Satisfaction', 'label_pl' => 'Zadowolonych klientów', 'label_pt' => 'Satisfação dos Clientes'],
                        ['value' => '10+',  'label_en' => 'Years Experience',    'label_pl' => 'Lat doświadczenia',      'label_pt' => 'Anos de Experiência'],
                    ],
                ],
                'is_active'   => true,
                'sort_order'  => 1,
            ],
            // -------------------------------------------------------
            // Trust Strip (logos / social proof)
            // -------------------------------------------------------
            [
                'key'         => 'trust_strip',
                'label'       => 'Trust Strip / Logos',
                'title'       => ['en' => 'Trusted by UK Businesses', 'pl' => 'Zaufali nam przedsiębiorcy z całego UK', 'pt' => 'Empresas do Reino Unido Confiam em Nós'],
                'subtitle'    => null,
                'body'        => null,
                'button_text' => null,
                'button_url'  => null,
                'image_path'  => null,
                'extra'       => [
                    'section_label_en' => 'Trusted By',
                    'section_label_pl' => 'Zaufali nam',
                    'section_label_pt' => 'Confiaram em nós',
                    'badges' => [
                        ['text' => '⭐ 5.0 Google Reviews'],
                        ['text' => '🔒 GDPR Compliant'],
                        ['text' => '🇬🇧 UK-Based Team'],
                        ['text' => '⚡ PageSpeed 95+'],
                    ],
                    'clients' => [
                        ['name' => 'Hargreaves Solicitors'],
                        ['name' => 'NTS Direct'],
                        ['name' => 'Oakfield Dental'],
                        ['name' => 'Pinnacle Recruitment'],
                        ['name' => 'Coastal Escapes'],
                        ['name' => 'Bloom & Grow'],
                    ],
                ],
                'is_active'   => true,
                'sort_order'  => 2,
            ],
            // -------------------------------------------------------
            // Services Section
            // -------------------------------------------------------
            [
                'key'         => 'services',
                'label'       => 'Services Section',
                'title'       => ['en' => 'Everything You Need to Succeed Online',    'pl' => 'Wszystko, czego potrzebujesz do sukcesu online',                'pt' => 'Tudo o Que Precisa para Ter Sucesso Online'],
                'subtitle'    => ['en' => 'From your first website to a full digital transformation — we have the expertise to make it happen.',
                                  'pl' => 'Od pierwszej strony internetowej po pełną transformację cyfrową — mamy wiedzę i doświadczenie, by to zrealizować.',
                                  'pt' => 'Desde o seu primeiro website a uma transformação digital completa — temos a expertise para o concretizar.'],
                'body'        => null,
                    'button_text' => ['en' => 'See All Services', 'pl' => 'Zobacz wszystkie usługi', 'pt' => 'Ver Todos os Serviços'],
                'button_url'  => '/services',
                'image_path'  => null,
                'extra'       => [
                    'section_label_en' => 'Services',
                    'section_label_pl' => 'Oferta',
                    'section_label_pt' => 'Serviços',
                    'services' => [
                        [
                            'icon'           => 'monitor',
                            'title_en'       => 'Brochure Websites',
                            'title_pl'       => 'Strony wizytówkowe',
                            'title_pt'       => 'Sites Institucionais',
                            'description_en' => 'Professional, mobile-first websites that create the right first impression and generate enquiries.',
                            'description_pl' => 'Profesjonalne strony firmowe mobile-first, które budują zaufanie i generują zapytania.',
                            'description_pt' => 'Websites profissionais mobile-first que criam a primeira impressão certa e geram pedidos de contacto.',
                            'price_from'     => '£799',
                            'link'           => '/services/brochure-websites',
                        ],
                        [
                            'icon'           => 'shopping-cart',
                            'title_en'       => 'E-Commerce Stores',
                            'title_pl'       => 'Sklepy e-commerce',
                            'title_pt'       => 'Lojas E-Commerce',
                            'description_en' => 'Sell online with confidence. WooCommerce and headless solutions tailored to your products.',
                            'description_pl' => 'Szybkie, bezpieczne sklepy online z integracją płatności i systemu zamówień.',
                            'description_pt' => 'Venda online com confiança. Soluções WooCommerce e headless adaptadas aos seus produtos.',
                            'price_from'     => '£2,999',
                            'link'           => '/services/ecommerce',
                        ],
                        [
                            'icon'           => 'code',
                            'title_en'       => 'Web Applications',
                            'title_pl'       => 'Aplikacje internetowe',
                            'title_pt'       => 'Aplicações Web',
                            'description_en' => 'Bespoke Laravel and React applications. Customer portals, SaaS platforms, booking systems.',
                            'description_pl' => 'Dedykowane aplikacje Laravel i React. Portale klientów, platformy SaaS, systemy rezerwacji.',
                            'description_pt' => 'Aplicações Laravel e React à medida. Portais de clientes, plataformas SaaS, sistemas de reservas.',
                            'price_from'     => '£5,999',
                            'link'           => '/services/web-applications',
                        ],
                        [
                            'icon'           => 'search',
                            'title_en'       => 'SEO & Digital Marketing',
                            'title_pl'       => 'SEO i Marketing Cyfrowy',
                            'title_pt'       => 'SEO e Marketing Digital',
                            'description_en' => 'Rank higher, attract more visitors, and convert them into paying customers.',
                            'description_pl' => 'Zaistniej w Google. Audyty SEO, optymalizacja on-page i strategia contentu.',
                            'description_pt' => 'Posicione-se mais alto, atraia mais visitantes e converta-os em clientes pagantes.',
                            'price_from'     => '£499',
                            'link'           => '/services/seo',
                        ],
                        [
                            'icon'           => 'bar-chart',
                            'title_en'       => 'Google Ads (PPC)',
                            'title_pl'       => 'Google Ads (PPC)',
                            'title_pt'       => 'Google Ads (PPC)',
                            'description_en' => 'Targeted pay-per-click campaigns that deliver measurable ROI from day one.',
                            'description_pl' => 'Kampanie płatne z realnym ROI – konfiguracja, optymalizacja i raportowanie.',
                            'description_pt' => 'Campanhas pagas por clique com ROI mensurável desde o primeiro dia.',
                            'price_from'     => '£399/mo',
                            'link'           => '/services/google-ads',
                        ],
                        [
                            'icon'           => 'zap',
                            'title_en'       => 'Meta / Pixel Ads',
                            'title_pl'       => 'Reklamy Meta / Pixel',
                            'title_pt'       => 'Anúncios Meta / Pixel',
                            'description_en' => 'Facebook & Instagram campaigns with Pixel tracking, retargeting and lookalike audiences.',
                            'description_pl' => 'Kampanie Facebook & Instagram z Pixelem, remarketingiem i grupami lookalike.',
                            'description_pt' => 'Campanhas no Facebook & Instagram com rastreamento Pixel, remarketing e públicos semelhantes.',
                            'price_from'     => '£349/mo',
                            'link'           => '/services/meta-ads',
                        ],
                        [
                            'icon'           => 'file-text',
                            'title_en'       => 'Content Creation',
                            'title_pl'       => 'Tworzenie treści',
                            'title_pt'       => 'Criação de Conteúdo',
                            'description_en' => 'Copywriting, blog articles, product descriptions and social media content in EN, PL and PT.',
                            'description_pl' => 'Copywriting, artykuły blogowe, opisy produktów i treści social media w PL, EN i PT.',
                            'description_pt' => 'Copywriting, artigos de blog, descrições de produtos e conteúdo para redes sociais em PT, EN e PL.',
                            'price_from'     => '£199/mo',
                            'link'           => '/services/content',
                        ],
                        [
                            'icon'           => 'shield',
                            'title_en'       => 'Security & Performance Audits',
                            'title_pl'       => 'Audyty bezpieczeństwa i wydajności',
                            'title_pt'       => 'Auditorias de Segurança e Desempenho',
                            'description_en' => 'In-depth security testing, Core Web Vitals optimisation and actionable performance reports.',
                            'description_pl' => 'Głęboka analiza bezpieczeństwa, optymalizacja Core Web Vitals i raporty z rekomendacjami.',
                            'description_pt' => 'Testes de segurança aprofundados, otimização de Core Web Vitals e relatórios de desempenho.',
                            'price_from'     => '£299',
                            'link'           => '/services/audits',
                        ],
                        [
                            'icon'           => 'settings',
                            'title_en'       => 'Website Maintenance',
                            'title_pl'       => 'Opieka nad stroną',
                            'title_pt'       => 'Manutenção de Website',
                            'description_en' => 'Keep your site fast, secure, and up to date with our monthly care plans.',
                            'description_pl' => 'Szybki hosting z SSL, backupami i opieką techniczną w pakiecie.',
                            'description_pt' => 'Manter o seu site rápido, seguro e atualizado com os nossos planos de manutenção mensais.',
                            'price_from'     => '£149/mo',
                            'link'           => '/services/maintenance',
                        ],
                    ],
                ],
                'is_active'   => true,
                'sort_order'  => 3,
            ],
            // -------------------------------------------------------
            // About Section
            // -------------------------------------------------------
            [
                'key'         => 'about',
                'label'       => 'About Section',
                'title'       => ['en' => 'A Digital Agency That Treats You Like a Partner',        'pl' => 'Agencja cyfrowa, która traktuje Cię jak partnera', 'pt' => 'Uma Agência Digital Que o Trata Como Parceiro'],
                'subtitle'    => ['en' => 'Based in Manchester. Working with businesses across the UK.', 'pl' => 'Siedziba w Manchesterze. Współpracujemy z firmami w całym UK.', 'pt' => 'Sediados em Manchester. A trabalhar com empresas em todo o Reino Unido.'],
                'body'        => [
                    'en' => '<p>We\'re a small, dedicated team of developers, designers, and digital marketers who genuinely care about your results. No account managers passing your project around — you work directly with the people building your website.</p><p>Since 2014, we\'ve delivered over 200 projects for businesses ranging from sole traders to multi-site enterprises. We\'re proud of every one of them.</p><p>We don\'t do cookie-cutter. Every project starts with a proper brief, a proper plan, and a commitment to delivering something you\'ll be proud of.</p>',
                    'pl' => '<p>Jesteśmy małym, zaangażowanym zespołem programistów, projektantów i marketerów, którym naprawdę zależy na Twoich wynikach. Żadnych pośredników — pracujesz bezpośrednio z ludźmi tworzącymi Twoją stronę.</p><p>Od 2014 roku zrealizowaliśmy ponad 200 projektów dla firm — od jednoosobowych działalności po rozbudowane przedsiębiorstwa. Jesteśmy z każdego z nich dumni.</p><p>Nie robimy szablonowych rozwiązań. Każdy projekt zaczyna się od porządnego briefu, planu i zaangażowania, aby dostarczyć coś, z czego będziesz dumny.</p>',
                    'pt' => '<p>Somos uma equipa pequena e dedicada de programadores, designers e profissionais de marketing que realmente se preocupam com os seus resultados. Sem intermediários — trabalha diretamente com as pessoas que constroem o seu website.</p><p>Desde 2014, já entregamos mais de 200 projetos para empresas de todos os tamanhos. Temos orgulho de todos eles.</p><p>Não fazemos soluções genéricas. Cada projeto começa com um brief adequado, um plano sólido e o compromisso de entregar algo de que se orgulhará.</p>',
                ],
                'button_text' => ['en' => 'Our Story', 'pl' => 'Nasza historia', 'pt' => 'A Nossa História'],
                'button_url'  => '/about',
                'image_path'  => null,
                'extra'       => [
                    'location'          => 'Manchester, UK',
                    'section_label_en'  => 'About Us',
                    'section_label_pl'  => 'O nas',
                    'section_label_pt'  => 'Sobre Nós',
                    'stats'      => [
                        ['value' => '200+', 'label_en' => 'Projects Delivered',  'label_pl' => 'Zrealizowanych projektów', 'label_pt' => 'Projetos Entregues'],
                        ['value' => '98%',  'label_en' => 'Client Satisfaction', 'label_pl' => 'Zadowolonych klientów',   'label_pt' => 'Satisfação do Cliente'],
                        ['value' => '10+',  'label_en' => 'Years Experience',    'label_pl' => 'Lat doświadczenia',        'label_pt' => 'Anos de Experiência'],
                    ],
                    'highlights' => [
                        [
                            'title_en' => 'Speed',
                            'title_pl' => 'Szybkość',
                            'title_pt' => 'Velocidade',
                            'body_en'  => 'Delivered in 2–6 weeks. Deadlines are not suggestions.',
                            'body_pl'  => 'Realizacje w 2–6 tygodniach. Terminy to nie sugestie.',
                            'body_pt'  => 'Entregues em 2–6 semanas. Os prazos não são sugestões.',
                        ],
                        [
                            'title_en' => 'Security',
                            'title_pl' => 'Bezpieczeństwo',
                            'title_pt' => 'Segurança',
                            'body_en'  => 'Audits, SSL, GDPR – your data and your clients\' data are protected.',
                            'body_pl'  => 'Audyty, SSL, GDPR – Twoje dane i dane klientów są chronione.',
                            'body_pt'  => 'Auditorias, SSL, RGPD – os seus dados e os dos seus clientes estão protegidos.',
                        ],
                        [
                            'title_en' => 'Results',
                            'title_pl' => 'Wyniki',
                            'title_pt' => 'Resultados',
                            'body_en'  => 'Conversion optimisation and SEO built in from day one.',
                            'body_pl'  => 'Optymalizacja konwersji i SEO wbudowane od pierwszego dnia.',
                            'body_pt'  => 'Otimização de conversão e SEO integrados desde o primeiro dia.',
                        ],
                        [
                            'title_en' => 'Partnership',
                            'title_pl' => 'Partnerstwo',
                            'title_pt' => 'Parceria',
                            'body_en'  => 'We don\'t disappear after launch. We\'re your tech partner.',
                            'body_pl'  => 'Nie znikamy po wdrożeniu. Jesteśmy Twoim tech-partnerem.',
                            'body_pt'  => 'Não desaparecemos após o lançamento. Somos o seu parceiro tecnológico.',
                        ],
                    ],
                ],
                'is_active'   => true,
                'sort_order'  => 4,
            ],
            // -------------------------------------------------------
            // Process Section
            // -------------------------------------------------------
            [
                'key'         => 'process',
                'label'       => 'How It Works / Process',
                'title'       => ['en' => 'Simple Process. Brilliant Results.',                                                   'pl' => 'Prosty proces. Doskonałe efekty.', 'pt' => 'Processo Simples. Resultados Brilhantes.'],
                'subtitle'    => ['en' => 'We\'ve refined our process over 10 years to make working with us as smooth as possible.', 'pl' => 'Przez 10 lat doskonaliliśmy nasz proces, by współpraca z nami przebiegała jak najsprawniej.', 'pt' => 'Apérféiçoamos o nosso processo ao longo de 10 anos para tornar a colaboração connosco o mais fluida possível.'],
                'body'        => null,
                'button_text' => null,
                'button_url'  => null,
                'image_path'  => null,
                'extra'       => [
                    'steps' => [
                        ['number' => '01',
                         'title_en' => 'Discovery Call',    'title_pl' => 'Rozmowa wstępna',      'title_pt' => 'Chamada de Descoberta',
                         'description_en' => 'We learn about your business, goals, and budget. We\'ll tell you honestly what\'s possible and what it will cost.',
                         'description_pl' => 'Poznajemy Twój biznes, cele i budżet. Powiem szczerze, co jest możliwe i ile to będzie kosztować.',
                         'description_pt' => 'Aprendemos sobre o seu negócio, objetivos e orçamento. Dizemos honestamente o que é possível e quanto custará.'],
                        ['number' => '02',
                         'title_en' => 'Quote & Brief',     'title_pl' => 'Wycena i brief',       'title_pt' => 'Proposta e Briefing',
                         'description_en' => 'You receive a detailed, fixed-price quote within 48 hours. Once approved, we create a full project brief.',
                         'description_pl' => 'Otrzymujesz szczegółową wycenę ze stałą ceną w ciągu 48 godzin. Po akceptacji tworzymy pełny brief projektu.',
                         'description_pt' => 'Receberá uma proposta detalhada e de preço fixo em 48 horas. Após aprovação, criamos um briefing completo.'],
                        ['number' => '03',
                         'title_en' => 'Design',            'title_pl' => 'Projekt graficzny',    'title_pt' => 'Design',
                         'description_en' => 'We design your website in Figma. You see exactly what you\'re getting before a line of code is written.',
                         'description_pl' => 'Projektujemy Twoją stronę w Figma. Widzisz dokładnie, co otrzymasz, zanim zostanie napisana choćby jedna linijka kodu.',
                         'description_pt' => 'Desenhamos o seu website no Figma. Vê exatamente o que vai receber antes de uma linha de código ser escrita.'],
                        ['number' => '04',
                         'title_en' => 'Build & Test',      'title_pl' => 'Budowa i testy',       'title_pt' => 'Desenvolvimento e Testes',
                         'description_en' => 'We build your site, test it across all devices and browsers, and run performance checks.',
                         'description_pl' => 'Budujemy stronę, testujemy na wszystkich urządzeniach i przeglądarkach oraz sprawdzamy wydajność.',
                         'description_pt' => 'Construímos o seu site, testamos em todos os dispositivos e browsers, e executamos verificações de desempenho.'],
                        ['number' => '05',
                         'title_en' => 'Launch & Handover', 'title_pl' => 'Wdrożenie i przekazanie', 'title_pt' => 'Lançamento e Entrega',
                         'description_en' => 'We handle the go-live, provide training, and give you everything you need to manage your site.',
                         'description_pl' => 'Obsługujemy wdrożenie, przeprowadzamy szkolenie i dajemy Ci wszystko, czego potrzebujesz do zarządzania stroną.',
                         'description_pt' => 'Tratamos do lançamento, fornecemos formação e damos-lhe tudo o que precisa para gerir o seu site.'],
                        ['number' => '06',
                         'title_en' => 'Ongoing Support',   'title_pl' => 'Wsparcie po wdrożeniu', 'title_pt' => 'Suporte Contínuo',
                         'description_en' => 'We\'re not gone after launch. Monthly maintenance plans, updates, and SEO available.',
                         'description_pl' => 'Nie znikamy po wdrożeniu. Dostępne miesięczne plany utrzymania, aktualizacje i SEO.',
                         'description_pt' => 'Não desaparecemos após o lançamento. Planos de manutenção mensal, atualizações e SEO disponíveis.'],
                    ],
                ],
                'is_active'   => true,
                'sort_order'  => 5,
            ],
            // -------------------------------------------------------
            // Portfolio / Case Studies Teaser
            // -------------------------------------------------------
            [
                'key'         => 'portfolio',
                'label'       => 'Portfolio Section',
                'title'       => ['en' => 'Recent Work We\'re Proud Of',                         'pl' => 'Ostatnie projekty, z których jesteśmy dumni', 'pt' => 'Trabalhos Recentes de Que Nos Orgulhamos'],
                'subtitle'    => ['en' => 'Every project is different. Here are a few recent examples.', 'pl' => 'Każdy projekt jest inny. Oto kilka ostatnich realizacji.', 'pt' => 'Cada projeto é único. Aqui estão alguns exemplos recentes.'],
                'body'        => null,
                'button_text' => ['en' => 'View All Projects', 'pl' => 'Zobacz wszystkie projekty', 'pt' => 'Ver Todos os Projetos'],
                'button_url'  => '/portfolio',
                'image_path'  => null,
                'extra'       => [
                    'section_label_en' => 'Portfolio',
                    'section_label_pl' => 'Portfolio',
                    'section_label_pt' => 'Portfolio',
                    'items' => [
                        [
                            'client'    => 'Hargreaves Solicitors',
                            'title_en'  => 'Solicitors Website Redesign',
                            'title_pl'  => 'Redesign strony kancelarii prawnej',
                            'title_pt'  => 'Redesign do Site de Advogados',
                            'tag_en'    => 'Brochure Website',
                            'tag_pl'    => 'Strona wizytówkowa',
                            'tag_pt'    => 'Site Institucional',
                            'desc_en'   => 'WCAG AA-compliant redesign for a Manchester solicitors firm. New case studies section, live chat integration.',
                            'desc_pl'   => 'Redesign strony dla kancelarii z Manchesteru zgodny z WCAG AA. Sekcja case studies, integracja live chat.',
                            'desc_pt'   => 'Redesign compatível com WCAG AA para uma firma de advogados em Manchester. Nova secção de casos, integração de live chat.',
                            'result_en' => '+40% contact form conversions',
                            'result_pl' => '+40% konwersji formularza kontaktowego',
                            'result_pt' => '+40% de conversões no formulário de contacto',
                            'tags'      => ['Laravel', 'Responsive', 'WCAG AA'],
                            'image'     => '/images/portfolio/hargreaves-solicitors.svg',
                            'link'      => '/portfolio/hargreaves-solicitors',
                        ],
                        [
                            'client'    => 'NTS Direct',
                            'title_en'  => 'B2B E-Commerce Platform',
                            'title_pl'  => 'Platforma e-commerce B2B',
                            'title_pt'  => 'Plataforma E-Commerce B2B',
                            'tag_en'    => 'E-Commerce',
                            'tag_pl'    => 'E-Commerce',
                            'tag_pt'    => 'E-Commerce',
                            'desc_en'   => 'Full B2B trade portal with 3,500+ SKUs, tiered pricing, custom quote builder and ERP integration.',
                            'desc_pl'   => 'Portal handlowy B2B z 3 500+ produktami, cenami poziomowymi, konfiguratorem wyceny i integracją ERP.',
                            'desc_pt'   => 'Portal comercial B2B completo com mais de 3.500 SKUs, preços por escalões, construtor de propostas e integração ERP.',
                            'result_en' => '£80k online sales in first month',
                            'result_pl' => '80 tys. £ sprzedaży online w pierwszym miesiącu',
                            'result_pt' => '£80 mil em vendas online no primeiro mês',
                            'tags'      => ['WooCommerce', 'B2B Portal', '3,500 SKUs'],
                            'image'     => '/images/portfolio/nts-direct.svg',
                            'link'      => '/portfolio/nts-direct',
                        ],
                        [
                            'client'    => 'Oakfield Dental',
                            'title_en'  => 'Dental Practice Website',
                            'title_pl'  => 'Strona kliniki dentystycznej',
                            'title_pt'  => 'Website de Clínica Dentária',
                            'tag_en'    => 'Healthcare Website',
                            'tag_pl'    => 'Strona medyczna',
                            'tag_pt'    => 'Website de Saúde',
                            'desc_en'   => 'CQC-compliant dental practice website with online booking, patient portal and Google Reviews integration.',
                            'desc_pl'   => 'Strona gabinetu dentystycznego zgodna z CQC, rezerwacja online, portal pacjenta, integracja Google Reviews.',
                            'desc_pt'   => 'Website de clínica dentária compatível com CQC, com marcações online, portal de pacientes e integração Google Reviews.',
                            'result_en' => '60% more new patient enquiries',
                            'result_pl' => '60% więcej zgłoszeń nowych pacjentów',
                            'result_pt' => '60% mais pedidos de novos pacientes',
                            'tags'      => ['Brochure', 'Booking Integration', 'CQC'],
                            'image'     => '/images/portfolio/oakfield-dental.svg',
                            'link'      => '/portfolio/oakfield-dental',
                        ],
                    ],
                ],
                'is_active'   => true,
                'sort_order'  => 6,
            ],
            // -------------------------------------------------------
            // Testimonials
            // -------------------------------------------------------
            [
                'key'         => 'testimonials',
                'label'       => 'Testimonials Section',
                'title'       => ['en' => 'What Our Clients Say', 'pl' => 'Co mówią nasi klienci', 'pt' => 'O Que Dizem os Nossos Clientes'],
                'subtitle'    => null,
                'body'        => null,
                'button_text' => null,
                'button_url'  => null,
                'image_path'  => null,
                'extra'       => [
                    'reviews' => [
                        [
                            'name'    => 'Robert Hargreaves',
                            'company' => 'Hargreaves Solicitors',
                            'rating'  => 5,
                            'text_en' => 'WebsiteExpert delivered exactly what we needed — a clean, professional site that our clients trust. The team were communicative throughout and delivered on time and on budget. Highly recommended.',
                            'text_pl' => 'WebsiteExpert dostarczył dokładnie to, czego potrzebowaliśmy — czystą, profesjonalną stronę, której nasi klienci ufają. Zespół komunikował się przez cały czas i dostarczył projekt na czas i w budżecie. Gorąco polecam.',
                            'text_pt' => 'A WebsiteExpert entregou exatamente o que precisávamos — um site limpo e profissional em que os nossos clientes confiam. A equipa comunicou durante todo o processo e entregou no prazo e no orçamento. Muito recomendado.',
                        ],
                        [
                            'name'    => 'Lisa Thornton',
                            'company' => 'NTS Direct',
                            'rating'  => 5,
                            'text_en' => 'Our new e-commerce platform has transformed our business. The B2B trade portal alone saved our sales team hours every week. The team understood our industry and delivered a product that really works.',
                            'text_pl' => 'Nasza nowa platforma e-commerce całkowicie przekształciła nasz biznes. Sam portal handlowy oszczędził naszemu zespołowi sprzedaży godziny tygodniowo. Zespół rozumiał naszą branżę i dostarczył produkt, który naprawdę działa.',
                            'text_pt' => 'A nossa nova plataforma de e-commerce transformou o nosso negócio. O portal B2B por si só poupou horas à nossa equipa de vendas. A equipa compreendeu a nossa indústria e entregou um produto que realmente funciona.',
                        ],
                        [
                            'name'    => 'Dr Priya Patel',
                            'company' => 'Oakfield Dental',
                            'rating'  => 5,
                            'text_en' => 'From the initial call to launch, everything was smooth and professional. Our new website has already brought us several new patients. Very happy with the service.',
                            'text_pl' => 'Od pierwszej rozmowy do uruchomienia wszystko przebiegało sprawnie i profesjonalnie. Nasza nowa strona już przyciągnęła kilku nowych pacjentów. Bardzo zadowolona z usługi.',
                            'text_pt' => 'Desde o primeiro contacto até ao lançamento, tudo correu de forma suave e profissional. O nosso novo website já nos trouxe vários novos pacientes. Muito satisfeita com o serviço.',
                        ],
                        [
                            'name'    => 'Daniel Walsh',
                            'company' => 'Pinnacle Recruitment',
                            'rating'  => 5,
                            'text_en' => 'We were referred to WebsiteExpert by another client and we\'re so glad we made the call. They\'re building our custom job board and the quality has been exceptional throughout.',
                            'text_pl' => 'Zostaliśmy poleceni do WebsiteExpert przez innego klienta i bardzo cieszymy się, że zadzwoniliśmy. Budują dla nas niestandardową tablicę ogłoszeń o pracę i jakość przez cały czas jest wyjątkowa.',
                            'text_pt' => 'Fomos indicados à WebsiteExpert por outro cliente e ficámos muito satisfeitos por ter ligado. Estão a construir o nosso quadro de empregos personalizado e a qualidade tem sido excecional.',
                        ],
                    ],
                ],
                'is_active'   => true,
                'sort_order'  => 7,
            ],
            // -------------------------------------------------------
            // CTA Banner
            // -------------------------------------------------------
            [
                'key'         => 'cta_banner',
                'label'       => 'CTA Banner',
                'title'       => ['en' => 'Ready to Get Started?',                                                          'pl' => 'Gotowy, aby zacząć?',                                                    'pt' => 'Pronto para Começar?'],
                'subtitle'    => ['en' => 'Get a free, no-obligation quote in 48 hours. No jargon. No pressure. Just honest advice.', 'pl' => 'Bezpłatna wycena bez zobowiązań w 48 godziny. Bez żargonu. Bez nacisków. Tylko uczciwe porady.', 'pt' => 'Obtenha um orçamento gratuito em 48 horas. Sem jargão. Sem pressão. Apenas conselhos honestos.'],
                'body'        => null,
                'button_text' => ['en' => 'Get My Free Quote', 'pl' => 'Chcę bezpłatną wycenę', 'pt' => 'Quero o Meu Orçamento Gratuito'],
                'button_url'  => '#calculator',
                'image_path'  => null,
                'extra'       => [
                    'secondary_button_text_en' => 'Book a Discovery Call',
                    'secondary_button_text_pl' => 'Umów rozmowę',
                    'secondary_button_text_pt' => 'Agendar uma Chamada',
                    'secondary_button_url'     => '/contact',
                    'phone'                    => '0161 000 0000',
                    'email'                    => 'hello@websiteexpert.co.uk',
                ],
                'is_active'   => true,
                'sort_order'  => 8,
            ],
            // -------------------------------------------------------
            // Cost Calculator Section
            // -------------------------------------------------------
            [
                'key'         => 'cost_calculator',
                'label'       => 'Cost Calculator Section',
                'title'       => ['en' => 'How Much Will Your Project Cost?', 'pl' => 'Ile będzie kosztował Twój projekt?', 'pt' => 'Quanto Vai Custar o Seu Projeto?'],
                'subtitle'    => ['en' => 'Answer a few questions and get an instant quote estimate. No registration required.', 'pl' => 'Odpowiedz na kilka pytań i otrzymaj wstępną wycenę. Szybko, bez rejestracji.', 'pt' => 'Responda a algumas perguntas e obtenha uma estimativa instantânea. Sem registo necessário.'],
                'body'        => null,
                'button_text' => null,
                'button_url'  => null,
                'image_path'  => null,
                'extra'       => [
                    'section_label_en' => 'Cost Calculator',
                    'section_label_pl' => 'Kalkulator kosztów',
                    'section_label_pt' => 'Calculadora de Custos',
                    'steps' => [
                        ['question_en' => 'What type of project do you need?',       'question_pl' => 'Jakiego projektu potrzebujesz?',           'hint_en' => 'Choose the project type that best describes your needs.',            'hint_pl' => 'Wybierz typ projektu, który najlepiej opisuje Twoje potrzeby.'],
                        ['question_en' => 'How many pages do you need?',              'question_pl' => 'Ile podstron?',                            'hint_en' => 'E.g. Home, About, Services, Blog, Contact.',                         'hint_pl' => 'Np. Strona główna, O nas, Usługi, Blog, Kontakt.'],
                        ['question_en' => 'What level of design do you need?',        'question_pl' => 'Jaki poziom designu?',                     'hint_en' => 'Custom design means a unique graphic project from scratch.',         'hint_pl' => 'Custom design to indywidualny projekt graficzny od zera.'],
                        ['question_en' => 'Do you need a content management system?', 'question_pl' => 'Czy potrzebujesz systemu CMS?',            'hint_en' => 'A CMS lets you edit content without a developer.',                   'hint_pl' => 'CMS pozwala samodzielnie edytować treści bez programisty.'],
                        ['question_en' => 'Which integrations do you need?',          'question_pl' => 'Jakie integracje?',                        'hint_en' => 'You can choose multiple options or skip this step.',                 'hint_pl' => 'Możesz wybrać wiele opcji lub pominąć ten krok.'],
                        ['question_en' => 'Do you want an SEO package?',              'question_pl' => 'Pakiet SEO?',                              'hint_en' => 'Search engine optimisation — more organic traffic.',                 'hint_pl' => 'Optymalizacja pod wyszukiwarki – więcej ruchu organicznego.'],
                        ['question_en' => 'When do you need the project?',            'question_pl' => 'Kiedy potrzebujesz projektu?',             'hint_en' => 'Faster timelines require additional resources.',                     'hint_pl' => 'Szybsze terminy wymagają dodatkowych zasobów.'],
                        ['question_en' => 'Hosting & maintenance?',                   'question_pl' => 'Hosting i utrzymanie?',                    'hint_en' => 'Hosting prices shown as an annual add-on.',                         'hint_pl' => 'Ceny hostingu podane jako dopłata roczna.'],
                    ],
                    'result_title_en'        => 'Your Estimated Quote',
                    'result_title_pl'        => 'Twoja szacowana wycena',
                    'result_title_pt'        => 'O Seu Orçamento Estimado',
                    'result_subtitle_en'     => 'Estimate based on the information you provided.',
                    'result_subtitle_pl'     => 'Wycena orientacyjna na podstawie podanych informacji.',
                    'result_subtitle_pt'     => 'Estimativa com base nas informações fornecidas.',
                    'result_cost_label_en'   => 'Estimated project cost',
                    'result_cost_label_pl'   => 'Szacowany koszt projektu',
                    'result_cost_label_pt'   => 'Custo estimado do projeto',
                    'hosting_addon_label_en' => '+ hosting',
                    'hosting_addon_label_pl' => '+ hosting',
                    'hosting_addon_label_pt' => '+ alojamento',
                    'per_year_en'            => '/year',
                    'per_year_pl'            => '/rok',
                    'per_year_pt'            => '/ano',
                    'contact_title_en'       => "Enter your details and we'll send you a detailed quote.",
                    'contact_title_pl'       => 'Podaj swoje dane, żebyśmy mogli wysłać Ci szczegółową ofertę.',
                    'contact_title_pt'       => 'Introduza os seus dados e enviaremos um orçamento detalhado.',
                    'name_placeholder_en'    => 'Your name / company',
                    'name_placeholder_pl'    => 'Twoje imię / firma',
                    'name_placeholder_pt'    => 'O seu nome / empresa',
                    'email_placeholder_en'   => 'Your email',
                    'email_placeholder_pl'   => 'Twój email',
                    'email_placeholder_pt'   => 'O seu email',
                    'submit_btn_en'          => 'Send enquiry 🚀',
                    'submit_btn_pl'          => 'Wyślij zapytanie 🚀',
                    'submit_btn_pt'          => 'Enviar pedido 🚀',
                    'submitting_btn_en'      => 'Sending…',
                    'submitting_btn_pl'      => 'Wysyłanie…',
                    'submitting_btn_pt'      => 'A enviar…',
                    'success_msg_en'         => "✓ Done! We'll get back to you within 1 business day.",
                    'success_msg_pl'         => '✓ Gotowe! Odezwiemy się w ciągu 24h roboczych.',
                    'success_msg_pt'         => '✓ Enviado! Responderemos em 1 dia útil.',
                    'sent_to_en'             => 'Sent to:',
                    'sent_to_pl'             => 'Na adres:',
                    'sent_to_pt'             => 'Enviado para:',
                    'restart_en'             => 'Start over',
                    'restart_pl'             => 'Zacznij od nowa',
                    'restart_pt'             => 'Recomeçar',
                    'step_label_en'          => 'Step',
                    'step_label_pl'          => 'Krok',
                    'step_label_pt'          => 'Passo',
                    'step_of_en'             => 'of',
                    'step_of_pl'             => 'z',
                    'step_of_pt'             => 'de',
                    'pages_addon_en'         => 'Each page above 5: +£80',
                    'pages_addon_pl'         => 'Każda strona powyżej 5: +£80',
                    'pages_addon_pt'         => 'Cada página acima de 5: +£80',
                    'nav_next_en'            => 'Next →',
                    'nav_next_pl'            => 'Dalej →',
                    'nav_next_pt'            => 'Seguinte →',
                    'nav_back_en'            => '← Back',
                    'nav_back_pl'            => '← Wstecz',
                    'nav_back_pt'            => '← Voltar',
                    'nav_skip_en'            => 'Skip →',
                    'nav_skip_pl'            => 'Pomiń →',
                    'nav_skip_pt'            => 'Saltar →',
                    'nav_calc_en'            => 'Calculate Quote 🚀',
                    'nav_calc_pl'            => 'Oblicz wycenę 🚀',
                    'nav_calc_pt'            => 'Calcular Orçamento 🚀',
                    'integrations_chip_en'   => 'integrations',
                    'integrations_chip_pl'   => 'integracje',
                    'integrations_chip_pt'   => 'integrações',
                    'pages_chip_en'          => 'pages',
                    'pages_chip_pl'          => 'podstron',
                    'pages_chip_pt'          => 'páginas',
                ],
                'is_active'   => true,
                'sort_order'  => 10,
            ],
            // -------------------------------------------------------
            // FAQ Section
            // -------------------------------------------------------
            [
                'key'         => 'faq',
                'label'       => 'FAQ Section',
                'title'       => ['en' => 'Frequently Asked Questions',                'pl' => 'Najczęściej zadawane pytania',                        'pt' => 'Perguntas Frequentes'],
                'subtitle'    => ['en' => 'Can\'t find what you\'re looking for? Just ask us.', 'pl' => 'Nie możesz znaleźć odpowiedzi? Po prostu zapytaj.', 'pt' => 'Não encontra o que procura? Basta perguntar-nos.'],
                'body'        => null,
                'button_text' => ['en' => 'Contact Us', 'pl' => 'Skontaktuj się z nami', 'pt' => 'Contacte-nos'],
                'button_url'  => '/contact',
                'image_path'  => null,
                'extra'       => [
                    'items' => [
                        [
                            'question_en' => 'How long does a website take?',
                            'question_pl' => 'Ile czasu trwa stworzenie strony?',
                            'question_pt' => 'Quanto tempo demora a criar um website?',
                            'answer_en'   => 'A standard brochure website typically takes 3–5 weeks from kick-off to launch. E-commerce and web applications vary — we\'ll give you a clear timeline in your project brief.',
                            'answer_pl'   => 'Standardowa strona wizytówkowa trwa zazwyczaj 3–5 tygodni od startu do wdrożenia. Sklepy i aplikacje mogą trwać dłużej — podamy jasny harmonogram w briefie.',
                            'answer_pt'   => 'Um website institucional padrão demora geralmente 3 a 5 semanas do início ao lançamento. E-commerce e aplicações web variam — forneceremos um cronograma claro no briefing.',
                        ],
                        [
                            'question_en' => 'How much does a website cost?',
                            'question_pl' => 'Ile kosztuje strona internetowa?',
                            'question_pt' => 'Quanto custa um website?',
                            'answer_en'   => 'Brochure websites start from £799. E-commerce from £2,999. We always provide a fixed-price quote — no surprises.',
                            'answer_pl'   => 'Strony wizytówkowe od £799. Sklepy od £2 999. Zawsze podajemy stałą cenę — bez niespodzianek.',
                            'answer_pt'   => 'Sites institucionais a partir de £799. E-commerce a partir de £2.999. Fornecemos sempre um orçamento de preço fixo — sem surpresas.',
                        ],
                        [
                            'question_en' => 'Do you work with clients outside Manchester?',
                            'question_pl' => 'Czy pracujecie z klientami spoza Manchesteru?',
                            'question_pt' => 'Trabalham com clientes fora de Manchester?',
                            'answer_en'   => 'Yes! The vast majority of our work is done remotely. We work with clients all across the UK. We\'re always happy to arrange a video call.',
                            'answer_pl'   => 'Tak! Zdecydowana większość naszych projektów jest realizowana zdalnie. Współpracujemy z firmami z całego UK. Zawsze chętnie umawiamy się na videocall.',
                            'answer_pt'   => 'Sim! A grande maioria do nosso trabalho é realizada remotamente. Trabalhamos com clientes em todo o Reino Unido. Estamos sempre disponíveis para uma videochamada.',
                        ],
                        [
                            'question_en' => 'What do I need to provide?',
                            'question_pl' => 'Co muszę dostarczyć?',
                            'question_pt' => 'O que preciso de fornecer?',
                            'answer_en'   => 'Typically: your logo (or brief for a new one), any text/content for the site, and any specific photos. We can help with content and photography if needed.',
                            'answer_pl'   => 'Zazwyczaj: logo (lub brief do nowego), treści na stronę i ewentualne zdjęcia. W razie potrzeby możemy pomóc z contentem i fotografią.',
                            'answer_pt'   => 'Normalmente: o seu logótipo (ou briefing para um novo), qualquer texto/conteúdo para o site e fotos específicas. Podemos ajudar com conteúdo e fotografia se necessário.',
                        ],
                        [
                            'question_en' => 'Will my website work on mobile?',
                            'question_pl' => 'Czy strona będzie działać na urządzeniach mobilnych?',
                            'question_pt' => 'O meu website vai funcionar em dispositivos móveis?',
                            'answer_en'   => 'Absolutely. Every website we build is designed mobile-first and tested on a wide range of devices and screen sizes.',
                            'answer_pl'   => 'Oczywiście. Każda strona, którą budujemy, jest projektowana mobile-first i testowana na szerokim zakresie urządzeń i rozmiarów ekranów.',
                            'answer_pt'   => 'Absolutamente. Cada website que construímos é desenhado mobile-first e testado num vasto leque de dispositivos e tamanhos de ecrã.',
                        ],
                        [
                            'question_en' => 'Do you offer payment plans?',
                            'question_pl' => 'Czy oferujecie plany ratalne?',
                            'question_pt' => 'Oferecem planos de pagamento?',
                            'answer_en'   => 'Yes. For larger projects we\'re happy to discuss staged payments. We typically take a 40–50% deposit, with the balance on delivery or split across milestones.',
                            'answer_pl'   => 'Tak. Przy większych projektach chętnie omawiamy płatności etapowe. Zazwyczaj pobieramy zaliczkę 40–50%, a resztę przy dostarczeniu lub w ratach według kamieni milowych.',
                            'answer_pt'   => 'Sim. Para projetos maiores, estamos dispostos a discutir pagamentos faseados. Tipicamente pedimos um depósito de 40–50%, com o restante na entrega ou dividido por marcos.',
                        ],
                        [
                            'question_en' => 'Will I be able to update my website myself?',
                            'question_pl' => 'Czy będę mógł samodzielnie aktualizować stronę?',
                            'question_pt' => 'Vou conseguir atualizar o meu website sozinho?',
                            'answer_en'   => 'Yes. We build with a CMS (WordPress or our own Filament-based system) and provide training and a user guide so you can manage your content confidently.',
                            'answer_pl'   => 'Tak. Budujemy z CMS (WordPress lub nasz własny system oparty na Filament) i zapewniamy szkolenie oraz przewodnik, abyś mógł zarządzać treściami samodzielnie.',
                            'answer_pt'   => 'Sim. Construímos com CMS (WordPress ou o nosso próprio sistema baseado em Filament) e fornecemos formação e um guia para que possa gerir o seu conteúdo com confiança.',
                        ],
                    ],
                ],
                'is_active'   => true,
                'sort_order'  => 9,
            ],
            // -------------------------------------------------------
            // Navbar
            // -------------------------------------------------------
            [
                'key'         => 'navbar',
                'label'       => 'Navigation Bar',
                'title'       => ['en' => 'Navigation', 'pl' => 'Nawigacja', 'pt' => 'Navega\u00e7\u00e3o'],
                'subtitle'    => null,
                'body'        => null,
                'button_text' => null,
                'button_url'  => null,
                'image_path'  => null,
                'extra'       => [
                    'brand_name'  => 'WebsiteExpert',
                    'cta_text_en' => 'Free Quote',
                    'cta_text_pl' => 'Bezpłatna wycena',
                    'cta_text_pt' => 'Orçamento Gratuito',
                    'cta_href'    => '#contact',
                    'links'       => [
                        ['label_en' => 'About Us',        'label_pl' => 'O nas',      'label_pt' => 'Sobre Nós',    'href' => '#about'],
                        ['label_en' => 'Services',        'label_pl' => 'Oferta',     'label_pt' => 'Serviços',     'href' => '#services'],
                        ['label_en' => 'Portfolio',       'label_pl' => 'Portfolio',  'label_pt' => 'Portfolio',    'href' => '#portfolio'],
                        ['label_en' => 'Cost Calculator', 'label_pl' => 'Kalkulator', 'label_pt' => 'Calculadora',  'href' => '#calculate'],
                        ['label_en' => 'Contact',         'label_pl' => 'Kontakt',    'label_pt' => 'Contacto',     'href' => '#contact'],
                    ],
                ],
                'is_active'   => true,
                'sort_order'  => 0,
            ],
            // -------------------------------------------------------
            // Contact Section
            // -------------------------------------------------------
            [
                'key'         => 'contact',
                'label'       => 'Contact Section',
                'title'       => ['en' => "Let's talk about your project",                                                    'pl' => 'Porozmawiajmy o Twoim projekcie',                                                     'pt' => 'Vamos Falar do Seu Projeto'],
                'subtitle'    => ['en' => "Get in touch and we'll reply within 24 business hours. First 30 min of consultation is free.",
                                  'pl' => 'Napisz do nas, a odezwiemy się w ciągu 24 godzin roboczych. Pierwsze 30 minut konsultacji jest bezpłatne.',
                                  'pt' => 'Entre em contacto e responderemos em 24 horas úteis. Os primeiros 30 min de consulta são gratuitos.'],
                'body'        => null,
                'button_text' => null,
                'button_url'  => null,
                'image_path'  => null,
                'extra'       => [
                    'section_label_en'       => 'Contact',
                    'section_label_pl'       => 'Kontakt',
                    'section_label_pt'       => 'Contacto',
                    'email'                  => 'hello@websiteexpert.co.uk',
                    'phone'                  => '+44 000 000 000',
                    'phone_href'             => 'tel:+44000000000',
                    'privacy_url'            => '/privacy-policy',
                    'submit_btn_en'          => 'Send message',
                    'submit_btn_pl'          => 'Wyślij wiadomość',
                    'submit_btn_pt'          => 'Enviar mensagem',
                    'success_msg_en'         => "✓ Message sent! We'll be in touch shortly.",
                    'success_msg_pl'         => '✓ Wiadomość wysłana! Odezwiemy się wkrótce.',
                    'success_msg_pt'         => '✓ Mensagem enviada! Entraremos em contacto em breve.',
                    'error_msg_en'           => 'Please fill in the required fields and accept the privacy policy.',
                    'error_msg_pl'           => 'Uzupełnij wymagane pola i zaznacz zgodę na przetwarzanie danych.',
                    'error_msg_pt'           => 'Por favor preencha os campos obrigatórios e aceite a política de privacidade.',
                    'gdpr_text_en'           => 'I agree to the processing of my personal data for the purpose of responding to this enquiry, in accordance with the',
                    'gdpr_text_pl'           => 'Wyrażam zgodę na przetwarzanie moich danych osobowych w celu odpowiedzi na zapytanie, zgodnie z',
                    'gdpr_text_pt'           => 'Concordo com o tratamento dos meus dados pessoais para responder a este pedido, de acordo com a',
                    'gdpr_link_text_en'      => 'privacy policy',
                    'gdpr_link_text_pl'      => 'polityką prywatności',
                    'gdpr_link_text_pt'      => 'política de privacidade',
                    'label_name_en'          => 'Full name',
                    'label_name_pl'          => 'Imię i nazwisko',
                    'label_name_pt'          => 'Nome completo',
                    'placeholder_name_en'    => 'John Smith',
                    'placeholder_name_pl'    => 'Jan Kowalski',
                    'placeholder_name_pt'    => 'João Silva',
                    'label_company_en'       => 'Company',
                    'label_company_pl'       => 'Firma',
                    'label_company_pt'       => 'Empresa',
                    'placeholder_company_en' => 'Company name',
                    'placeholder_company_pl' => 'Nazwa firmy',
                    'placeholder_company_pt' => 'Nome da empresa',
                    'label_email_en'         => 'Email',
                    'label_email_pl'         => 'Email',
                    'label_email_pt'         => 'Email',
                    'label_phone_en'         => 'Phone',
                    'label_phone_pl'         => 'Telefon',
                    'label_phone_pt'         => 'Telefone',
                    'label_nip_en'           => 'VAT / NIP',
                    'label_nip_pl'           => 'NIP / VAT',
                    'label_nip_pt'           => 'NIF / VAT',
                    'label_project_type_en'  => 'Project type',
                    'label_project_type_pl'  => 'Rodzaj projektu',
                    'label_project_type_pt'  => 'Tipo de projeto',
                    'label_contact_pref_en'  => 'Preferred contact',
                    'label_contact_pref_pl'  => 'Preferowany kontakt',
                    'label_contact_pref_pt'  => 'Contacto preferido',
                    'label_message_en'       => 'Message',
                    'label_message_pl'       => 'Wiadomość',
                    'label_message_pt'       => 'Mensagem',
                    'placeholder_message_en' => 'Tell us about your project or ask a question...',
                    'placeholder_message_pl' => 'Opisz swój projekt lub pytanie...',
                    'placeholder_message_pt' => 'Descreva o seu projeto ou faça uma pergunta...',
                    'project_types' => [
                        ['value' => 'wizytowka', 'label_en' => 'Brochure website',     'label_pl' => 'Strona wizytówkowa', 'label_pt' => 'Site institucional'],
                        ['value' => 'ecommerce', 'label_en' => 'E-commerce store',     'label_pl' => 'Sklep e-commerce',   'label_pt' => 'Loja e-commerce'],
                        ['value' => 'aplikacja', 'label_en' => 'Web application',      'label_pl' => 'Aplikacja webowa',   'label_pt' => 'Aplicação web'],
                        ['value' => 'seo',       'label_en' => 'SEO / Positioning',    'label_pl' => 'SEO / Pozycjonowanie', 'label_pt' => 'SEO / Posicionamento'],
                        ['value' => 'reklama',   'label_en' => 'Advertising campaign', 'label_pl' => 'Kampania reklamowa', 'label_pt' => 'Campanha publicitária'],
                        ['value' => 'inne',      'label_en' => 'Other',                'label_pl' => 'Inne',               'label_pt' => 'Outro'],
                    ],
                    'contact_prefs' => [
                        ['value' => '',        'label_en' => '– Any method –',  'label_pl' => '– Dowolna forma –',   'label_pt' => '– Qualquer método –'],
                        ['value' => 'email',   'label_en' => 'Email',           'label_pl' => 'Email',               'label_pt' => 'Email'],
                        ['value' => 'telefon', 'label_en' => 'Phone',           'label_pl' => 'Telefon',             'label_pt' => 'Telefone'],
                        ['value' => 'teams',   'label_en' => 'Microsoft Teams', 'label_pl' => 'Microsoft Teams',     'label_pt' => 'Microsoft Teams'],
                        ['value' => 'meet',    'label_en' => 'Google Meet',     'label_pl' => 'Google Meet',         'label_pt' => 'Google Meet'],
                    ],
                ],
                'is_active'   => true,
                'sort_order'  => 11,
            ],
            // -------------------------------------------------------
            // Footer
            // -------------------------------------------------------
            [
                'key'         => 'footer',
                'label'       => 'Footer',
                'title'       => ['en' => 'Footer', 'pl' => 'Stopka'],
                'subtitle'    => null,
                'body'        => null,
                'button_text' => null,
                'button_url'  => null,
                'image_path'  => null,
                'extra'       => [
                    'brand_name'    => 'WebsiteExpert',
                    'tagline_en'    => 'We create websites and web apps that work for your business.',
                    'tagline_pl'    => 'Tworzymy strony i aplikacje internetowe, które pracują na Twój biznes.',
                    'tagline_pt'    => 'Criamos websites e aplicações web que trabalham para o seu negócio.',
                    'copyright_en'  => 'All rights reserved.',
                    'copyright_pl'  => 'Wszelkie prawa zastrzeżone.',
                    'copyright_pt'  => 'Todos os direitos reservados.',
                    'built_with_en' => 'Designed and built with ❤️ in Poland',
                    'built_with_pl' => 'Zaprojektowane i zbudowane z ❤️ w Polsce',
                    'built_with_pt' => 'Desenhado e construído com ❤️ na Polónia',
                    'social'        => [
                        ['key' => 'linkedin',  'url' => '#', 'label' => 'LinkedIn'],
                        ['key' => 'facebook',  'url' => '#', 'label' => 'Facebook'],
                        ['key' => 'instagram', 'url' => '#', 'label' => 'Instagram'],
                    ],
                    'nav_groups' => [
                        [
                            'title_en' => 'Services',
                            'title_pl' => 'Usługi',
                            'title_pt' => 'Serviços',
                            'links'    => [
                                ['label_en' => 'Brochure Websites', 'label_pl' => 'Strony wizytówkowe', 'label_pt' => 'Sites institucionais', 'href' => '#services'],
                                ['label_en' => 'E-Commerce Stores', 'label_pl' => 'Sklepy e-commerce',  'label_pt' => 'Lojas e-commerce',     'href' => '#services'],
                                ['label_en' => 'SEO',               'label_pl' => 'SEO',                'label_pt' => 'SEO',                  'href' => '#services'],
                                ['label_en' => 'Google Ads',        'label_pl' => 'Google Ads',         'label_pt' => 'Google Ads',           'href' => '#services'],
                                ['label_en' => 'Web Hosting',       'label_pl' => 'Hosting WWW',        'label_pt' => 'Alojamento Web',       'href' => '#services'],
                            ],
                        ],
                        [
                            'title_en' => 'Company',
                            'title_pl' => 'Firma',
                            'title_pt' => 'Empresa',
                            'links'    => [
                                ['label_en' => 'About Us',        'label_pl' => 'O nas',              'label_pt' => 'Sobre Nós',          'href' => '#about'],
                                ['label_en' => 'Portfolio',       'label_pl' => 'Portfolio',          'label_pt' => 'Portfolio',          'href' => '#portfolio'],
                                ['label_en' => 'Cost Calculator', 'label_pl' => 'Kalkulator kosztów', 'label_pt' => 'Calculadora',        'href' => '#calculate'],
                                ['label_en' => 'Contact',         'label_pl' => 'Kontakt',            'label_pt' => 'Contacto',           'href' => '#contact'],
                                ['label_en' => 'Client Portal',   'label_pl' => 'Portal Klienta',     'label_pt' => 'Portal do Cliente',  'href' => '/portal'],
                            ],
                        ],
                        [
                            'title_en' => 'Legal',
                            'title_pl' => 'Prawne',
                            'title_pt' => 'Legal',
                            'links'    => [
                                ['label_en' => 'Privacy Policy', 'label_pl' => 'Polityka prywatności', 'label_pt' => 'Política de Privacidade', 'href' => '/privacy-policy'],
                                ['label_en' => 'Terms of Use',   'label_pl' => 'Regulamin',            'label_pt' => 'Termos de Uso',          'href' => '/terms-and-conditions'],
                                ['label_en' => 'Cookies',        'label_pl' => 'Cookies',              'label_pt' => 'Cookies',                'href' => '/cookies'],
                            ],
                        ],
                    ],
                ],
                'is_active'   => true,
                'sort_order'  => 12,
            ],
        ];

        foreach ($sections as $data) {
            SiteSection::updateOrCreate(['key' => $data['key']], $data);
        }
    }
}
